### ISSUE TITLE
uchardet: source url no longer available

### ISSUE THREAD

**Issue by jgmdev** [mesonbuild/wrapdb#1004]
Hi, freedesktop.org retired all their repo mirrors from github, making the meson uchardet wrap fail to download the sources. It may be better to use this download location https://www.freedesktop.org/software/uchardet/releases/ or https://gitlab.freedesktop.org/uchardet/uchardet/-/releases, also version 0.8.0 of uchardet was released.

**Comment by jpakkane** [comment]
WrapDB is maintained by volunteers and we have limited time to fix these things. So patches welcome, I guess.

**Comment by neheb** [comment]
https://github.com/mesonbuild/wrapdb/pull/1008
