### ISSUE TITLE
request: OpenSSL

### ISSUE THREAD

**Issue by nazar-pc** [mesonbuild/wrapdb#109]
I don't know if I'll have time to work on this, but ability to build static OpenSSL using Meson would be a huge deal for many projects.

https://github.com/nodejs/node/tree/master/deps/openssl can be used as a reference. It uses GYP and allows to build OpenSSL without regular procedure that involves Perl, so it must be possible to translate GYP configs to Meson more or less mechanically and get the same result.

**Comment by eli-schwartz** [comment]
Anyone who manages this will be my hero. :D That being said, yeah -- it's a non-trivial build system to port over. It's been mentioned multiple times in IRC...

**Comment by nazar-pc** [comment]
FYI I started working on this.

From initial testing looks like the approach I described should work, even though it wouldn't be very pretty. Will update once I have something to show.
