### ISSUE TITLE
New wrap: libui

### ISSUE THREAD

**Issue by ebraminio** [mesonbuild/wrapdb#11]
Wondering if is possible to have https://github.com/andlabs/libui in wrap db? It is itself in meson and I was able to use the project as a subproject using this wrap https://github.com/filfat/NXTBrowser/blob/37f5992c3/subprojects/libui.wrap

**Comment by legeana** [comment]
It is. I have created the repository: https://github.com/mesonbuild/libui
Please submit the upstream.wrap: https://mesonbuild.com/Adding-new-projects-to-wrapdb.html#how-to-contribute-a-new-wrap
If possible please try to use an actual release and/or ask the upstream to create them if necessary. This is not required.
