### ISSUE TITLE
gdbm wrap won't compile

### ISSUE THREAD

**Issue by 2talltech** [mesonbuild/wrapdb#1130]
I've been hacking at this for hours. So far, I fixed one issue.
```
../subprojects/gdbm-1.23/src/gdbmdefs.h:31:3: error: #error "Unsupported off_t size, contact GDBM maintainer.  What crazy system is this?!?"
   31 | # error "Unsupported off_t size, contact GDBM maintainer.  What crazy system is this?!?"
```

In gdbm's meson.build:
`
conf.set('SIZEOF_OFF_T', cc.sizeof('off_t'))`

should be:

`conf.set('SIZEOF_OFF_T', cc.sizeof('off_t', prefix : '#include <sys/types.h>')`

I can't crack this one:
```
../subprojects/gdbm-1.23/src/gdbmopen.c:26:25: error: unknown type name ‘blksize_t’; did you mean ‘size_t’?
   26 | compute_directory_size (blksize_t block_size,
      |                         ^~~~~~~~~
      |                         size_t
```

There are other issues with undeclared defines.

In the mean time, does someone have a gdbm.pc file for pkg-config handy? It's been a day, and I might have to let this sit for another time.

**Comment by 2talltech** [comment]
Well, I'm silly. gdbm is found by meson on it's own on my system. No need to declare it as a dependency.

**Comment by neheb** [comment]
Weird. Wonder why it’s not failing in CI.

**Comment by 2talltech** [comment]
Alright, gdbm is NOT found by meson, my mistake. To use my system gdbm, this works for me:
```
cc = meson.get_compiler('c')
gdbm = cc.find_library('gdbm', dirs : ['/usr/lib/x86_64-linux-gnu'], static: true)
```
Then add gdbm to executable dependencies.

For the wrap, this is a Devuan system "Devuan GNU/Linux 5 (daedalus)" (essentially Debian 12 "Bookworm").

**Comment by neheb** [comment]
sounds like an OS bug. Closing.
