### ISSUE TITLE
openjpeg support

### ISSUE THREAD

**Issue by dabrain34** [mesonbuild/wrapdb#12]
Here is a meson port for openjpeg:

https://github.com/uclouvain/openjpeg/pull/1242

**Comment by legeana** [comment]
I looked at the library and it uses `libopenjp2` as a pkgconfig name.
https://github.com/mesonbuild/libopenjp2 is created. Please open a pull request.
Note that the expected dependency name should be `libopenjp2_dep` according to the guidelines.
https://mesonbuild.com/Adding-new-projects-to-wrapdb.html#choosing-the-repository-name
