### ISSUE TITLE
Make it possible to run CI's scripts in forks and locally

### ISSUE THREAD

**Issue by nazar-pc** [mesonbuild/wrapdb#121]
The way CI is currently configured makes it basically impossible to check things before submitting PR and then annoying everyone watching the repo with test commits.

The first issue is trilom/file-changes-action action that works in a very strange way in general and I would argue is basically broken: https://github.com/trilom/file-changes-action/issues/116

The second issue related to that is that it is not possible to run `sanity_checks.py` locally due to the fact that it relies in `files.json` in the home folder.

From what I understand it is basically necessary to find out what files have changed as of commit on which the script is running relatively to:
* `master` if not on `master` branch
* relatively to older `master` revision right before current commit otherwise

If there was a script that does this just by using `git diff` or something, that would make it much nicer to work with.

**Comment by eli-schwartz** [comment]
Ah, so *that*s why I got nonsense errors when I pushed a new PR branch to this repo.

**Comment by xclaesse** [comment]
Maybe instead of checking changed files to know which wraps needs to be sanity checked, I could just rely on the new release tags. As long as the PR is not making new releases, who cares if it's not conformant?
