### ISSUE TITLE
simdjson wrap doesn't work correctly when linking

### ISSUE THREAD

**Issue by shanoaice** [mesonbuild/wrapdb#1218]
I am the author of #1210, which adds `gnu_symbol_visibility: 'hidden'` to the meson.build files. I have just tested this wrap out on my project and it seems that with this flag simdjson won't link properly, producing the following errors:

```
/usr/sbin/ld: shale.p/src_auth.cpp.o: in function `simdjson::fallback::numberparsing::(anonymous namespace)::parse_float_fallback(unsigned char const*, double*)':
/home/shanoa/Projects/shale-onedrive/builddir/../subprojects/simdjson-3.3.0/singleheader/simdjson.h:13986:(.text+0x22e): undefined reference to `simdjson::internal::from_chars(char const*)'
/usr/sbin/ld: shale.p/src_auth.cpp.o: in function `simdjson::fallback::numberparsing::(anonymous namespace)::parse_float_fallback(unsigned char const*, unsigned char const*, double*)':
/home/shanoa/Projects/shale-onedrive/builddir/../subprojects/simdjson-3.3.0/singleheader/simdjson.h:14001:(.text+0x2bf): undefined reference to `simdjson::internal::from_chars(char const*, char const*)'
```

which should be related to calling `.get_int64()` method on parsed JSON documents.

It seems like that with this option some symbols are hidden incorrectly, causing a linking failure. I am not sure whether this is an upstream issue or not.

**Comment by neheb** [comment]
It's an upstream issue: https://github.com/simdjson/simdjson/blob/1875ed65503a2ea9cc4010581bb0fe2a4c40b5bc/CMakeLists.txt#L77

**Comment by shanoaice** [comment]
> It's an upstream issue: [simdjson/simdjson@`1875ed6`/CMakeLists.txt#L77](https://github.com/simdjson/simdjson/blob/1875ed65503a2ea9cc4010581bb0fe2a4c40b5bc/CMakeLists.txt#L77)

Got that, then I should probably open an issue there? But meanwhile should we revert this change so that the wrap works correctly?

**Comment by neheb** [comment]
They probably know about it. I doubt they care about fixing. I’m guessing it’s related to a missing external template declaration.

Revert the change yes. Or comment it out and add a comment why.
