### ISSUE TITLE
Feature request: provide an import path to be used with `protoc` for compiling *.proto files

### ISSUE THREAD

**Issue by klokik** [mesonbuild/wrapdb#1259]
Protobuf ships with a bunch of standard *.proto files (any, descriptor, empty, timestamp) that are expected to be found, if imported within another proto file, during `protoc` executable invocation.

Protoc accepts a list of `--proto_path pathXXX` arguments to specify import search locations. Unfortunately if using protobuf as a subproject, one can not expect to find these at standard locations (like /usr/share/protobuf/google/....). Thus cannot use protoc from subproject to generate sources at meson project build time.

I didn't found any example within existing wrapdb files on how it may be specified elsewhere, outside of `protobuf` packagefiles itself, which is sell aware of its sources locations.

Suggestion: populate `protobuf` dependency variables with a path to this location.

**Comment by klokik** [comment]
Looking towards something like

```
protobuf_dep = declare_dependency(
  compile_args: imp,
  link_with: libprotobuf,
  include_directories: incdir,
  variables: {
    'proto_path': meson.current_source_dir() / 'src',
  }
)
```

and then

```
protobuf_dep = dependency('protobuf')
protoc = find_program('protoc')

gen_sources = custom_target('proto-gen',
  ..., command: [protoc, '--proto_path=' + protobuf_dep.get_variable('proto_path'), '@INPUT@', ....], ....)

```

**Comment by klokik** [comment]
@dvrogozh any comments on that?

**Comment by dcbaker** [comment]
I feel like we should just set that argument in the  protobuf override itself so this is transparent

**Comment by klokik** [comment]
@dcbaker sorry, I don't get it, it seems one can not add arguments to `meson.override_findprogram()` without creating, say, wrapper script.

Or do you suggest modifying `protoc` to add build-time defined proto_path?

**Comment by klokik** [comment]
One more option to explore: `protoc` searches for `include` directory in it's and a few parent directories. So creating a custom target that either creates a symlink targeting source directory, or copies a few files to private build directory might be cleaner.

**Comment by dvrogozh** [comment]
> @dvrogozh any comments on that?

protobuf usage on our side is quite limited. We do not use .proto files from protobuf project as includes. As for the suggestions above, I personally am fine with your initial proposal. I also don't understand @dcbaker comment above, example code would be nice to have to clarify. I don't like idea on the copying though.

**Comment by klokik** [comment]
@dvrogozh, @dcbaker  please review #1263

It should be transparent for protoc users now.
