### ISSUE TITLE
new wrap: libgpiod

### ISSUE THREAD

**Issue by amboar** [mesonbuild/wrapdb#129]
upstream url: https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/
version: 1.6.3

**Comment by xclaesse** [comment]
Please follow the README to submit new wraps, the documetation at mesonbuild.com is outdated.

https://github.com/mesonbuild/wrapdb/blob/master/README.md

**Comment by amboar** [comment]
ah, I see. Let me follow that instead.

**Comment by eli-schwartz** [comment]
I finally opened a PR to update the docs: https://github.com/mesonbuild/meson/pull/9102
