### ISSUE TITLE
new wraps: rdkafka, yajl

### ISSUE THREAD

**Issue by jcaesar** [mesonbuild/wrapdb#13]
name: rdkafka
upstream url: https://github.com/edenhill/librdkafka
version: 1.4.0
[preview](https://github.com/jcaesar/crappywraps/tree/88e62570548c6da23fe2148f04379a31c838f67f/rdkafka/librdkafka-1.4.0)

name: yajl (or yajl-2?)
upstream url: https://github.com/lloyd/yajl/
version: 2.1.0
[preview](https://github.com/jcaesar/crappywraps/tree/88e62570548c6da23fe2148f04379a31c838f67f/yajl/yajl-2.1.0)
(Upstream seems dead, but it still seems to be in use in quite a few packages, a quick look at the debian packages showed mpd, icinga, libvirt, kafkacat, and kodi.)

**Comment by legeana** [comment]
https://github.com/mesonbuild/rdkafka

**Comment by legeana** [comment]
https://github.com/mesonbuild/yajl

**Comment by legeana** [comment]
FTR the naming is based on the existence of 
```
src/CMakeLists.txt:  "${GENERATED_DIR}/rdkafka.pc"
src/CMakeLists.txt:CONFIGURE_FILE(yajl.pc.cmake ${shareDir}/yajl.pc)
```
