### ISSUE TITLE
Release didn't work: openssl_3.0.8-2

### ISSUE THREAD

**Issue by hrxi** [mesonbuild/wrapdb#1307]
https://github.com/mesonbuild/wrapdb/actions/runs/6961444629/job/18943037589

```
subprojects/packagefiles/openssl/generator.sh: line 6: util/libcrypto.num: No such file or directory
```

Does the release script get executed in an environment that is different from the one I get when I execute `meson setup <builddir> -Dwraps=openssl`?

**Comment by eli-schwartz** [comment]
The release script invokes the generator from packagefiles. It looks like you ran that from the wrong location -- the openssl repository is cloned around line 30.

**Comment by neheb** [comment]
Just noticed python3 is ran in generator.sh. Bad practice as some OS do not have python3, just python (which is 3).

generator.sh should be converted to Python IMO.

**Comment by hrxi** [comment]
> The release script invokes the generator from packagefiles. It looks like you ran that from the wrong location -- the openssl repository is cloned around line 30.

It doesn't have the unpacked https://www.openssl.org/source/openssl-3.0.8.tar.gz around?
