### ISSUE TITLE
rdkafka: Include paths for usage as a subproject are broken

### ISSUE THREAD

**Issue by jcaesar** [mesonbuild/wrapdb#1314]
Using the rdkafka wrap used to work with
```
#include <librdkafka/rdkafka.h>
```
because of this line
https://github.com/mesonbuild/wrapdb/blob/5db78cca6f28ff0f86b358c8c424728381dd5b85/subprojects/packagefiles/rdkafka/meson.build#L180
which got broken later
https://github.com/mesonbuild/wrapdb/blob/c02ad953c38c01c0acafa3d70205d0d4d6db7be4/subprojects/packagefiles/rdkafka/meson.build#L211
and was then improperly fixed
https://github.com/mesonbuild/wrapdb/blob/33cac3592eb615e524af00d548fc97c53bf1a32d/subprojects/packagefiles/rdkafka/meson.build#L217

(I know it's a one line fix, but I'm somewhat reluctant to submit patches after the last fiasco…)

**Comment by neheb** [comment]
ah ok.

**Comment by neheb** [comment]
Fixed assuming nothing else broke.
