### ISSUE TITLE
Alpine CI shouldn't run as root

### ISSUE THREAD

**Issue by ibc** [mesonbuild/wrapdb#1316]
Issue reported in actions/runner-images: https://github.com/actions/runner-images/issues/8915

Not sure if the problem (Alpine container runs as root) if in their side or here.

The issue is that the libuv wrap fails in its last version since libuv doesn't allow running its tests as root (for a good reason).

This is the PR trying to update libuv wrapdb to the latest libuv version, and it fails because the Alpine container tries to run libuv tests as root:

https://github.com/mesonbuild/wrapdb/pull/1315

**Comment by neheb** [comment]
PRs welcome. All containers run as root.

**Comment by jmillan** [comment]
Fixed here #1315

**Comment by benoit-pierre** [comment]
See `check_new_release` in `sanity_checks.py`: https://github.com/mesonbuild/wrapdb/blob/master/tools/sanity_checks.py#L367 (and #1326 for a fix).

**Comment by ibc** [comment]
Got it. Good fix BTW.
