### ISSUE TITLE
Wrap for LuaJIT

### ISSUE THREAD

**Issue by manipuladordedados** [mesonbuild/wrapdb#1325]

**Comment by benoit-pierre** [comment]
I have a version here: https://github.com/benoit-pierre/koreader/tree/bpierre/subprojects/packagefiles/luajit/overlay.

**Comment by manipuladordedados** [comment]
Good, do you have any plans to submit it to the wraps repository?

**Comment by kasper93** [comment]
@benoit-pierre: Have you considered upstreaming it? I'm currently looking into options (for win32 ci build of [mpv](https://github.com/mpv-player/mpv)), don't really want to duplicate work of maintaining the wrap locally, so centralized one in wrapdb would be cool.

I also have seen https://github.com/arch1t3cht/Aegisub/tree/feature/subprojects/packagefiles/luajit which works for our needs, but again there is this friction accessing the wrap.

**Comment by benoit-pierre** [comment]
Since the project does not do releases, an exception would be needed to use snapshots from the Github mirror. @eli-schwartz, @jpakkane, @neheb?

**Comment by eli-schwartz** [comment]
Yes please. This is a reasonable situation for making an exception (I'm well aware of luajit's issue).

**Comment by benoit-pierre** [comment]
See #1506.

**Comment by UnixY2K** [comment]
#1506 got merged so I think this can be closed
