### ISSUE TITLE
Project proposal for WrapDB-UI

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#14]
### Hello everyone.

I’m planning on building an application for `WrapDB dev tools` to make it easier on developers that tend to understand graphical representation over terminal.

I have some questions about the Wrap systems tools such as following:

### Questions:

* Is `wrapdev-tools` the main kit for developing wraps?

* Is there a plans to extend the tools?

* Have all of the currently available commands been documented?

* If so where can I find the documentation?

* What is the usual process of creating a new wrap?

* Is wrapdb the only wrap service available for wrap dependencies?

* Are there some things I should know before I start building the application?

**Comment by jpakkane** [comment]
The documentation we have is [at the web site](https://mesonbuild.com/Wrap-dependency-system-manual.html). Granted it's not the greatest, so patches are most definitely welcome.

> Is wrapdb the only wrap service available for wrap dependencies?

Not really. The wrap files themselves contain just urls, they can point to anywhere. For example companies might want to host their internal wrap service if they prefer. The various `meson wrap` commands only use the wrapdb, though.

**Comment by michaelbadcrumble** [comment]
I’ve read some of the documentation and there is actually lots of potential for a wrap file studio. So here is what I got so far, and if I’m wrong please correct me.

Following actions to perform in the application:
* Init
* Check
* Publish
* Watch
* Serve 
* Review 

Wrap file generator types:
* wrap-file
* wrap-git
* wrap-hg
* wrap-svn

However I have additional questions, is there a way to validate that a wrap repository works?

Is there anything like the Meson introspection API I should know about?

**Comment by michaelbadcrumble** [comment]
I will see what I can do with this information and the lovely documentation for `Wrap` related information.

If there are some more parts that make up the tool kit would like to know.
