### ISSUE TITLE
spdlog c++ standard should be upgraded

### ISSUE THREAD

**Issue by NewbiZ** [mesonbuild/wrapdb#1404]
### Intent
I want to use the `spdlog` wrap with the standard `std::format` instead of the bundled `fmt::format`. This is possible since C++20 onward. `spdlog` offers this possibility with the use of `-DSPDLOG_USE_STD_FORMAT`.

### Description of the issue
The current `spdlog` wrap uses `default_options: ['cpp_std=c++14']`.
This is incompatible with the `std_format` feature, because it specifically checks for `__cpp_lib_format`, which is only defined if the C++ standard is set to 20 onward. This effectively makes the `std_format` feature unusable.

### References
- The `spdlog` wrap forces the c++ standard to c++ 14: https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/spdlog/meson.build#L6
- The `spdlog` wrap exposes the `std_format` feature and checks that `__cpp_lib_format` is defined: https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/spdlog/meson.build#L17
- The `__cpp_lib_format` feature test macro is only defined on C++20 onward: https://en.cppreference.com/w/cpp/feature_test#cpp_lib_format

**Comment by neheb** [comment]
Best thing to do is remove that default option ImO

**Comment by stephanlachnit** [comment]
Can't you just overwrite the default option?
```meson
dependency('spdlog', default_options: ['cpp_std=c++20'])
```
But it's probably good to remove the default anyway.
