### ISSUE TITLE
jansson: -Wformat-invalid-specifier

### ISSUE THREAD

**Issue by patrickdowling** [mesonbuild/wrapdb#1460]
Noticed this in passing and it reproduces in this repo. Apologies if I'm missing something obvious...
```
../subprojects/jansson-2.14/src/dump.c:238:65: warning: invalid conversion specifier 'P' [-Wformat-invalid-specifier]
```

AFAICT this comes from [jansson/meson.build:58](https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/jansson/meson.build#L58)
```
cdata.set_quoted('JSON_INTEGER_FORMAT', 'PRId64')
```
so the resulting format string is `...%" "PRId64"` which is not what we wanted given `PRId64` is macro?

- The obvious change to use `cdata.set` doesn't compile without also patching `dump.c` to `#include <inttypes.h>`. Not sure why since `HAVE_INTTYPES_H` is 1.

- Using `cdata.set_quoted(..., 'lld')` compiles without warnings, but ignores all the usual config. That smells like a "works for me" solution :)

While poking around I found a related [suggestion in the jansson repo](https://github.com/akheron/jansson/issues/659) to switch to `intmax_t` which might also make it easier.

FWIW
```
Host machine cpu family: x86_64
Host machine cpu: x86_64
jansson| C compiler for the host machine: ccache cc (clang 15.0.0 "Apple clang version 15.0.0 (clang-1500.1.0.2.5)")
```

Thanks!

**Comment by neheb** [comment]
fixed.

**Comment by patrickdowling** [comment]
Thanks!
