### ISSUE TITLE
`meson wrap status` says out of date when wrap is up to date

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/wrapdb#149]
I just installed the most recent `gtest` subproject using `meson wrap install gtest` (v1.0.11-1).

When running `meson wrap status`, I get this output:
```
 gtest not up to date. Have 1.11.0 1, but 1.11.0 1 is available.
```

Seems to be a bug?

Meson: 0.59.1
OS: Fedora 34

**Comment by xclaesse** [comment]
Thanks for the report. It is a bug in meson and not wrapdb. I made a fix: https://github.com/mesonbuild/meson/pull/9189.
