### ISSUE TITLE
new wrap for glfw

### ISSUE THREAD

**Issue by swarnimarun** [mesonbuild/wrapdb#15]
name: glfw
forked upstream: https://github.com/henry4k/glfw-meson (also this, slightly old)
primary upstream: https://github.com/glfw/glfw (it's cmake)
version: 3.3.2 on primary

I am not sure if there is a wrap for it already and I am too dumb to find it. But being able to just use wraptools for glfw would be very nice.

**Comment by legeana** [comment]
https://github.com/glfw/glfw/blob/master/CMake/glfw3.pc.in
The wrap will be named glfw3 according to our style guide, based on the pkg-config file.
I don't think we have it as a wrap.
Repository created: https://github.com/mesonbuild/glfw3
Please submit a pull with the wrap itself.

**Comment by swarnimarun** [comment]
@legeana aah didn't know about the style guide. And thanks for the quick addition. :)

**Comment by swarnimarun** [comment]
Will create a PR ASAP. :)
