### ISSUE TITLE
ConfigParser not parsing `%` in openblas sourceforge url

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/wrapdb#151]
I'm creating a wrap for openblas-0.3.17, and I've set the source_url to `https://sourceforge.net/projects/openblas/files/v0.3.17/OpenBLAS%%200.3.17%%20version.zip/`, but python requires a `%` escape character to parse this string in `sanity_checks.py`:
```
Traceback (most recent call last):
  File "/home/user/wrapdb/tools/sanity_checks.py", line 127, in test_releases
    self.check_source_url(name, wrap_section, ver)
  File "/home/user/wrapdb/tools/sanity_checks.py", line 147, in check_source_url
    source_url = wrap_section['source_url']
  File "/usr/lib64/python3.9/configparser.py", line 1258, in __getitem__
    return self._parser.get(self._name, key)
  File "/usr/lib64/python3.9/configparser.py", line 799, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/usr/lib64/python3.9/configparser.py", line 395, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.9/configparser.py", line 442, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%200.3.17%20version.zip/'
```

But even though the url is checked in python, it is accessed in meson, so then it doesn't get the correct address:
```
meson.build:8:2: ERROR: could not get https://sourceforge.net/projects/openblas/files/v0.3.17/OpenBLAS%%200.3.17%%20version.zip/
```

How can I get around this?  Solution could just be finding a different url that works to download it, but I'm not sure how to locate one.

**Comment by xclaesse** [comment]
Sourceforge is really the worst, always surprised people are still using it in 2021...

But openblas seems actually on github instead: http://www.openblas.net/ points to https://github.com/xianyi/OpenBLAS/releases/download/v0.3.15/OpenBLAS-0.3.15.tar.gz

**Comment by xclaesse** [comment]
0.3.17 is there: https://github.com/xianyi/OpenBLAS/releases/download/v0.3.17/OpenBLAS-0.3.17.tar.gz

**Comment by danielcjacobs** [comment]
Thanks!

Before closing the issue, it seems like it’s possible that future wraps could have urls with “%20”.  Do you think this needs a solution, or should we assume it’s rare enough that there’s other workarounds?
