### ISSUE TITLE
Fail to download gtest patch from wrapdb

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/wrapdb#156]
When running meson build, with `gtest` as a subproject, the build gets stuck on
`Downloading gtest patch from https://wrapdb.mesonbuild.com/v2/gtest_1.11.0-1/get_patch`

There's no error, but it won't do anything once it reaches this point.
If I click the url, it downloads the gtest zip easily...why can't it build?

**Comment by xclaesse** [comment]
Have you tried to retry, or wget that URL, in case it's just a temporary network issue? Works for me.

**Comment by xclaesse** [comment]
(I understand the problem could be URGENT for you, but that's a nice way to communicate)

**Comment by danielcjacobs** [comment]
It's been a recurring issue on my system. `wget` didn't work either, so it must be a network issue even though my network is working fine

**Comment by danielcjacobs** [comment]
after running for about 10 minutes, `wget` failed with a 403 forbidden

**Comment by danielcjacobs** [comment]
It was an issue with my network and their server

**Comment by xclaesse** [comment]
pretty sure it's an issue on your side. https://wrapdb.mesonbuild.com/v2/gtest_1.11.0-1/get_patch redirects to github  https://github.com/mesonbuild/wrapdb/releases/download/gtest_1.11.0-1/gtest_1.11.0-1_patch.zip. Does that link work for you?

**Comment by danielcjacobs** [comment]
it's definitely an issue on my end, albeit a strange one. The other url doesn't work either
