### ISSUE TITLE
Install a specific wrap version

### ISSUE THREAD

**Issue by danielcjacobs** [mesonbuild/wrapdb#157]
[The docs](https://mesonbuild.com/Using-wraptool.html) allow me to list available wrap versions, but they don't say how I can use this information to install a previous wrap version?

Is this even possible, and if so, how?

**Comment by xclaesse** [comment]
The table there contains all versions: https://mesonbuild.com/Wrapdb-projects.html. Just download the .wrap file in your subprojects/.

**Comment by danielcjacobs** [comment]
oh okay, I guess I was asking if there was any way to do it using the `meson wrap` tool

**Comment by xclaesse** [comment]
no, `meson wrap install` will always take latest one. Feel free to open a PR that adds --version option.
