### ISSUE TITLE
tree-sitter wrap doesn't produce linkable library

### ISSUE THREAD

**Issue by ethindp** [mesonbuild/wrapdb#1608]
I'm trying to include tree-sitter but it only produces a shared library, but not a library that my compiler can link to. (In this case, it's a `.lib` on windows, but I think this might also happen on Linux and other platforms.)

**Comment by benoit-pierre** [comment]
As in the correct symbols are not exported? It might be missing some compilation flags to enable the correct `declspec(…)` exports, or a def file for linking the library on Windows.

**Comment by ethindp** [comment]
@benoit-pierre No, as in no `.lib` file is generated at all. The only generated files are `tree-sitter.dll`, `tree-sitter.dll.p`, and `tree-sitter.pdb`.

**Comment by jpakkane** [comment]
Which is to say it's [probably this](https://mesonbuild.com/FAQ.html#my-project-works-fine-on-linux-and-mingw-but-fails-to-link-with-msvc-due-to-a-missing-lib-file-fatal-error-lnk1181-why),

**Comment by benoit-pierre** [comment]
Compiling with `-DTS_PUBLIC=__declspec(dllexport)` on Windows might fix it.

And we should add `gnu_symbol_visibility : 'hidden'` for other platforms.

**Comment by benoit-pierre** [comment]
Wait, no, it's going to cause issues (redefined macro)…

For some reason they removed support for it: https://github.com/tree-sitter/tree-sitter/pull/3128.

So a def file is needed.

**Comment by benoit-pierre** [comment]
Configuring the project to build a static library should work too.

**Comment by ethindp** [comment]
Is that something I can do from my meson.build? Or does that need to be a revision to the patch? (Should probably update to 0.22.6 while we're at it if we neeed to modify the wrap.)

**Comment by benoit-pierre** [comment]
Try configuring your project with `meson setup -Dtree-sitter:default_library=static …`.

**Comment by ethindp** [comment]
That worked. Thanks! Now I just need to add that globally I'd say.
