### ISSUE TITLE
Delete vs_module_defs from cmocka?

### ISSUE THREAD

**Issue by gszy** [mesonbuild/wrapdb#1612]
I’m not sure about the exact purpose of the `vs_module_defs` argument and the file it refers to, but here’s my problem with it: I have a C project with some cmocka-based unit tests. In a native Linux build the test binaries are linked to system `libcmocka.so.0` and work OK. In a MinGW-w64 build (where cmocka is a subproject) they’re linked to `cmocka.dll`, which does not exist, because Meson builds `libcmocka.dll`.

It turned out (thanks to `@elibrokeit`’s help on IRC) that the issue comes from the file that `vs_module_defs` refers to, where the library name is set to `cmocka.dll`. When I delete the argument, the test binaries are linked to `libcmocka.dll` and work OK. If you think the argument is not necessary, I can provide a PR.

**Comment by eli-schwartz** [comment]
Well, I also said the library should be overridden to respect the name from the .def file. If you remove it entirely then a mingw toolchain will act like Unix and export every symbol from the code, and MSVC will export none of them -- thereby breaking the DLL.

That file lists the exact set of symbols that should be exported.

**Comment by neheb** [comment]
Probably better to fix the name.

**Comment by gszy** [comment]
In [the `library()` function documentation](https://mesonbuild.com/Reference-manual_functions.html#library) I’ve found parameter `name_prefix`, which could be set to empty string for Windows to always produce `cmocka.dll`, but I’m not sure it’s a good idea, especially since the description reads:

> […] By default this is lib on all platforms and compilers, except for MSVC shared libraries where it is omitted to follow convention […]

So it seems `libcmocka.dll` is the correct name for MinGW-w64 builds and `cmocka.dll` would be the correct name for MSVC builds. Perhaps I have to change something in my project? Why does it want to link with the MSVC library if I compile it with MinGW? I have pushed a minimal example to [Codeberg](https://codeberg.org/gs/meson-cmocka-test), could you have a look at it?

**Comment by neheb** [comment]
def file says cmocka.dll. Which means you would have to get rid of lib for MinGW

**Comment by gszy** [comment]
Oh, I see there are some precedents:
https://github.com/search?q=repo%3Amesonbuild%2Fwrapdb%20name_prefix&type=code
I’m preparing a PR.
