### ISSUE TITLE
Install SDL2 wrap includes to SDL2/SDL.h?

### ISSUE THREAD

**Issue by knuxify** [mesonbuild/wrapdb#1713]
The SDL2 wrap places headers directly in include/SDL.h. The code I'm trying to build with meson uses SDL2/SDL.h. Most distros seem to provide SDL2/SDL.h, so it ends up taking priority.

Is there a way to make the wrap place its includes to the SDL2 subdirectory?

**Comment by jpakkane** [comment]
From memory, the official docs of SDL say to use `#include"SDL.h"` and nothing else. [See also this](https://nullprogram.com/blog/2023/01/08/).

If this is true, the "correct" change would be to fix the include directives in source files.

**Comment by knuxify** [comment]
Indeed, seems like a codebase-side issue; looks like the SDL2/SDL.h include was an old hack that was never dropped. I'll replace it with just SDL.h. Thanks for the hint!
