### ISSUE TITLE
Wrong c version for sqlite3

### ISSUE THREAD

**Issue by KaruroChori** [mesonbuild/wrapdb#1747]
`sqlite3` on linux systems requires `gnu11` or similar in place of the standard c, as it uses functions as `lstat` which are otherwise not available.

**Comment by bgilbert** [comment]
`sqlite3.c` defines `_GNU_SOURCE`, so `lstat` should be available even on older glibc (&lt; 2.20) which doesn't expose it by default.  Could you post more information about your build environment and the error you're seeing?

**Comment by KaruroChori** [comment]
That is a good question.
I tried to reproduce this issue again without the fix of setting `gnu11`, but the problem I observed just few hours ago is nowhere to be seen. For context, I was testing the new support of zig in 1.6.0.rc2. So that might have been the root cause, as I was getting few more oddities like libcurl not being detected.
