### ISSUE TITLE
new wrap: libwebsockets

### ISSUE THREAD

**Issue by falk-werner** [mesonbuild/wrapdb#18]
upstream url: [https://github.com/warmcat/libwebsockets](https://github.com/warmcat/libwebsockets)
version: 4.0.10

**Comment by legeana** [comment]
The upstream URL you specified doesn't actually appear to be the upstream.
https://libwebsockets.org/ specifies a different repository. Do you know anything about it?

The name `libwebsockets` is approved based on the `libwebsockets.pc`.

**Comment by falk-werner** [comment]
Sorry, I never noticed this before. But I think you are right: github seems to be a mirror. At least there is link named "Github Mirror" on libwebsockets homepage:
[https://libwebsockets.org/git/libwebsockets/tree/?h=v4.0-stable](https://libwebsockets.org/git/libwebsockets/tree/?h=v4.0-stable
)

**Comment by legeana** [comment]
```
$ mesonwrap new_repo --homepage=https://libwebsockets.org --directory=~/wrapdb/libwebsockets libwebsockets
Repository created: https://github.com/mesonbuild/libwebsockets
```
