### ISSUE TITLE
New wrap: teensyduino-cores

### ISSUE THREAD

**Issue by phillipjohnston** [mesonbuild/wrapdb#19]
Hello,

I would like to create a wrap file + build overlay for Paul Stoffregen's Teensy SDK for the Arduino environment. The only problem is that the upstream repository has a very generic name ("cores"), which does not sufficiently identify the project. I propose that the wrap repository is namd "teensyduino-cores" to match [the true project name](https://www.pjrc.com/teensy/teensyduino.html).

upstream url: https://github.com/PaulStoffregen/cores
version: [1.52](https://github.com/PaulStoffregen/cores/releases/tag/1.52)

**Comment by legeana** [comment]
Thank you for contributing this :)

Repository created: https://github.com/mesonbuild/teensyduino-cores
