### ISSUE TITLE
new wrap: vulkan_headers

### ISSUE THREAD

**Issue by stephanlachnit** [mesonbuild/wrapdb#20]
upstream url: https://github.com/KhronosGroup/Vulkan-Headers
version: 1.2.124

Already maintain it here: https://github.com/stephanlachnit/vulkanheaders-wrap 
I know, wrong format, but as long as it's not in the WarpDB it doesn't matter anyway.

**Comment by legeana** [comment]
The CMake library doesn't have a `*.pc` file. However there is a library name, `Vulkan-Headers`. I propose to name it as such. In lowercase for consistency with [Homebrew](https://formulae.brew.sh/formula/vulkan-headers).

It also seems `v1.2.141` is available. You don't have to port your wrap to the new version though, feel free to submit the PR against master, I will change it accordingly.

Repository created: https://github.com/mesonbuild/vulkan-headers

**Comment by stephanlachnit** [comment]
Ah sorry typo, yes I meant 1.2.141 of course.
