### ISSUE TITLE
New wrap: Loguru

### ISSUE THREAD

**Issue by nnooney** [mesonbuild/wrapdb#22]
upstream url: https://github.com/emilk/loguru
version: 2.1.0

Perhaps this should be called loguru-cpp to not be confused with the python logging library loguru here: https://github.com/Delgan/loguru.

**Comment by nnooney** [comment]
Also thank you very much for maintaining WrapDB and helping me share my contributions.

**Comment by legeana** [comment]
> Also thank you very much for maintaining WrapDB and helping me share my contributions.

Thank you for your contributions!

> Perhaps this should be called loguru-cpp

https://github.com/mesonbuild/emilk-loguru already exists :) Please open a PR.
