### ISSUE TITLE
Add Taglib

### ISSUE THREAD

**Issue by SeanOMik** [mesonbuild/wrapdb#260]
The library has a website [here](https://taglib.org/), and its GitHub is [here](https://github.com/taglib/taglib).

**Comment by jpakkane** [comment]
Unfortunately the maintainers of WrapDB don't have much time to create new build definitions, but anyone can do that themselves and submit a PR. Thanks.

**Comment by tp-m** [comment]
Wasn't that just added a day or two ago?

https://mesonbuild.com/Wrapdb-projects.html

**Comment by jpakkane** [comment]
Huh, apparently it was. That should have had a `Closes: 260` in the commit message so this would have closed automatically.

**Comment by eli-schwartz** [comment]
I think probably the person who contributed taglib wasn't closely following whether or not requests were opened for it. :p

(Also I forgot about this issue too...)
