### ISSUE TITLE
pugixml does not compile under openbsd

### ISSUE THREAD

**Issue by neheb** [mesonbuild/wrapdb#282]
Fixed upstream with https://github.com/zeux/pugixml/commit/81274bb026a40550cd80faf6c1855defbb87c430

```
../subprojects/pugixml-1.11.4/tests/test_document.cpp:746:9: error: use of undeclared identifier 'unlink'
                CHECK(unlink(path) == 0);
                      ^
```

**Comment by eli-schwartz** [comment]
Okay? This is an upstream bug, pugixml needs to release an updated tag.

**Comment by neheb** [comment]
I wouldn't say that. the wrap doesn't allow disabling the tests(which are not really relevant as a subproject).
