### ISSUE TITLE
Incomplete dependencies in libpng's meson.build

### ISSUE THREAD

**Issue by mstorsjo** [mesonbuild/wrapdb#3]
The meson.build that wrapdb provides, for libpng (verified on libpng 1.6.34, seems to be the same on newer versions as well), seems to be missing a dependency:

The meson.build has got a `zlib_dep` which is set as a dependency for the libpng library itself. The meson.build file also contains `png_test = executable('pngtest', 'pngtest.c', dependencies : png_dep)`, where pngtest.c directly includes `zlib.h`. If `zlib.h` isn't available in a compiler default include path, it isn't found for building the test executable.

Changing it into `png_test = executable('pngtest', 'pngtest.c', dependencies : [png_dep, zlib_dep])` seems to work for me.

**Comment by legeana** [comment]
I am not sure why it doesn't work as it is. Could you please provide some build logs?

From what I see

```
libpng_deps = [
        zlib_dep,
        cc.find_library('m', required : false),
]

libpng = library('png',
    src,
    dependencies : libpng_deps,
    c_args: c_args,
)

png_dep = declare_dependency(
    include_directories : include,
    link_with : libpng,
    dependencies : libpng_deps,  # >> this includes zlib_dep <<
)

png_test = executable('pngtest', 'pngtest.c', dependencies : png_dep)  # >> zlib_dep is transitively includes <<
```

So from how I see it should work. Maybe I am missing something

**Comment by mstorsjo** [comment]
If I understand it correctly, the include directories of zlib aren't added when building pngtest.c, as png_test doesn't have a direct dependency on zlib, only a transitive one (even though the libraries for static linking might be added transitively).

For reproducing, I'm doing something like this, with a mingw cross compiler from linux:
```sh
$ git clone https://github.com/centricular/zlib.git
$ cd zlib
$ mkdir build
$ cd build
$ meson .. --cross-file=../../cross-mingw-x86_64.meson --prefix=/prefix -Dlibdir=lib --buildtype=release
$ ninja install

$ cd ../..

$ wget ftp://ftp-osl.osuosl.org/pub/libpng/src/libpng16/libpng-1.6.34.tar.xz
$ tar -Jxvf libpng-1.6.34.tar.xz
$ wget -O libpng-1.6.34-1-wrap.zip https://wrapdb.mesonbuild.com/v1/projects/libpng/1.6.34/1/get_zip
$ unzip libpng-1.6.34-1-wrap.zip

$ export PKG_CONFIG_LIBDIR=/prefix/lib/pkgconfig

$ meson .. --cross-file=../../cross-mingw-x86_64.meson --prefix=/prefix -Dlibdir=lib --buildtype=release
$ ninja -v
[...]
[15/19] x86_64-w64-mingw32-gcc -Ipng@sha -I. -I.. -I/prefix/include -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -O3 -MD -MQ 'png@sha/pngwutil.c.obj' -MF 'png@sha/pngwutil.c.obj.d' -o 'png@sha/pngwutil.c.obj' -c ../pngwutil.c
[16/19] x86_64-w64-mingw32-gcc  -o libpng.dll 'png@sha/png.c.obj' 'png@sha/pngerror.c.obj' 'png@sha/pngget.c.obj' 'png@sha/pngmem.c.obj' 'png@sha/pngpread.c.obj' 'png@sha/pngread.c.obj' 'png@sha/pngrio.c.obj' 'png@sha/pngrtran.c.obj' 'png@sha/pngrutil.c.obj' 'png@sha/pngset.c.obj' 'png@sha/pngtrans.c.obj' 'png@sha/pngwio.c.obj' 'png@sha/pngwrite.c.obj' 'png@sha/pngwtran.c.obj' 'png@sha/pngwutil.c.obj' -Wl,--allow-shlib-undefined -Wl,-O1 -shared -Wl,--start-group -Wl,--out-implib=libpng.dll.a /prefix/lib/libz.dll.a -lm -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -Wl,--end-group
[17/19] /usr/local/bin/meson --internal symbolextractor libpng.dll 'png@sha/libpng.dll.symbols' --cross-host=windows
[18/19] x86_64-w64-mingw32-gcc -Ipngtest@exe -I. -I.. -I../ -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -O3 -MD -MQ 'pngtest@exe/pngtest.c.obj' -MF 'pngtest@exe/pngtest.c.obj.d' -o 'pngtest@exe/pngtest.c.obj' -c ../pngtest.c
FAILED: pngtest@exe/pngtest.c.obj 
x86_64-w64-mingw32-gcc -Ipngtest@exe -I. -I.. -I../ -fdiagnostics-color=always -pipe -Wall -Winvalid-pch -O3 -MD -MQ 'pngtest@exe/pngtest.c.obj' -MF 'pngtest@exe/pngtest.c.obj.d' -o 'pngtest@exe/pngtest.c.obj' -c ../pngtest.c
../pngtest.c:73:12: fatal error: zlib.h: No such file or directory
 #  include "zlib.h"
            ^~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

This was tested with meson 0.53.2.

**Comment by eli-schwartz** [comment]
This works fine for me:

```
# musl-gcc does not use the system include path, only /usr/lib/musl/include
$ CC=musl-gcc meson setup bdir-zlib --prefix=$PWD/pkg/usr -Dwraps=zlib --wipe
$ ninja -C bdir-zlib/ install
$ PKG_CONFIG_PATH=/home/eschwartz/git/mesonbuild/wrapdb/pkg/usr/lib/pkgconfig CC=musl-gcc meson setup bdir-libpng -Dwraps=libpng
$ ninja -C bdir-libpng
[1/2] musl-gcc -Isubprojects/libpng-1.6.37/pngtest.p -Isubprojects/libpng-1.6.37 -I../subprojects/libpng-1.6.37 -I/home/eschwartz/git/mesonbuild/wrapdb/pkg/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -MD -MQ subprojects/libpng-1.6.37/pngtest.p/pngtest.c.o -MF subprojects/libpng-1.6.37/pngtest.p/pngtest.c.o.d -o subprojects/libpng-1.6.37/pngtest.p/pngtest.c.o -c ../subprojects/libpng-1.6.37/pngtest.c
[2/2] musl-gcc  -o subprojects/libpng-1.6.37/pngtest subprojects/libpng-1.6.37/pngtest.p/pngtest.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/:$ORIGIN/../../../pkg/usr/lib' -Wl,-rpath-link,/home/eschwartz/git/mesonbuild/wrapdb/bdir-libpng/subprojects/libpng-1.6.37 -Wl,-rpath-link,/home/eschwartz/git/mesonbuild/wrapdb/bdir-libpng/../pkg/usr/lib -Wl,--start-group subprojects/libpng-1.6.37/libpng16.so.16.37.0 /home/eschwartz/git/mesonbuild/wrapdb/pkg/usr/lib/libz.so -lm -Wl,--end-group
```

As you can see, the libpng wrap caused the detected zlib include path to be added to the pngtest binary.

**Comment by neheb** [comment]
I assume this is fixed/not an issue.

**Comment by mstorsjo** [comment]
Sorry, I've meant to get back to this to set up a complete selfcontained reproducer with e.g. docker or something like that...

**Comment by mstorsjo** [comment]
I finally got around to retrying this, and yes, with the commands shown by @eli-schwartz above, the issue does seem to be fixed.

The older version history of wrapdb seems a bit hard to find, but at least downloadable artifacts are available. The fix seems to have been between https://wrapdb.mesonbuild.com/v2/libpng_1.6.34-1/get_patch and https://wrapdb.mesonbuild.com/v2/libpng_1.6.34-2/get_patch, where the diff looks like this:
```diff
diff -u libpng-1.6.34-1/meson.build libpng-1.6.34-2/meson.build
--- libpng-1.6.34-1/meson.build	2018-04-18 12:27:46.000000000 +0300
+++ libpng-1.6.34-2/meson.build	2018-06-02 21:54:30.000000000 +0300
@@ -10,6 +10,17 @@
   zlib_dep = dependency('zlib', fallback : ['zlib', 'zlib_dep'])
 endif
 
+c_args = []
+
+if host_machine.system() == 'windows'
+  c_args += ['-DPNG_BUILD_DLL']
+endif
+
+libpng_deps = [
+        zlib_dep,
+        cc.find_library('m', required : false),
+]
+
 libpng = library('png', [
         'png.c',
         'pngerror.c',
@@ -27,10 +38,8 @@
         'pngwtran.c',
         'pngwutil.c',
     ],
-    dependencies : [
-        zlib_dep,
-        cc.find_library('m', required : false),
-    ],
+    dependencies : libpng_deps,
+    c_args: c_args,
 )
 
 configure_file(
@@ -42,6 +51,7 @@
 png_dep = declare_dependency(
     include_directories : include,
     link_with : libpng,
+    dependencies : libpng_deps,
 )
 
 png_test = executable('pngtest', 'pngtest.c', dependencies : png_dep)
```

This fixes exactly what this issue explained was broken - that the zlib dependency wasn't added to the `png_test` executable, but now it is.

**Comment by mstorsjo** [comment]
> > The older version history of wrapdb seems a bit hard to find
> 
> We de-list all but the latest wrapdb revision of each upstream tagged release, because people rarely need to be shown the previous wrapdb bugfixes but it made the projects table bulky and difficult to find particular versions.
> 
> That being said, yes, they all correspond to tags here, and we don't remove old versions as people still need to download them if they installed that version and referenced that url. The naming scheme is programmatic and predictable as well. :)

Ah, I see. Although in this case, these tags seem to belong to the v1 history of wrapdb, so they all point at the same import commit in the current wrapdb repo.

**Comment by eli-schwartz** [comment]
The v1 API works a bit differently, yeah. Those were from when we used https://github.com/mesonbuild/libpng and similar.

When moving to the unified repo, we merged each individual repo in here, I think via subtrees? So it's... Somewhere, but not very direct. The old approach used branches without history to add new versions, as well, so it was difficult to compare.

**Comment by mstorsjo** [comment]
> The v1 API works a bit differently, yeah. Those were from when we used https://github.com/mesonbuild/libpng and similar.
> 
> When moving to the unified repo, we merged each individual repo in here, I think via subtrees? So it's... Somewhere, but not very direct. The old approach used branches without history to add new versions, as well, so it was difficult to compare.

Yeah, that's pretty much what I gathered from what I saw in that repo history.

Anyway, thanks - the issue is resolved (and has been for a long time), and I've at least seen a clear diff that shows where/when/how it was fixed, so everything is fine here :-)
