### ISSUE TITLE
new wrap: gRPC

### ISSUE THREAD

**Issue by ricardoaiglesias** [mesonbuild/wrapdb#30]
Upstream: https://github.com/grpc/grpc/tree/v1.30.0

It currently uses cmake + bazel/blaze, so I'm not sure how to make a "wrap" for it, while also creating the plugins one would use in the project (such as `grpc_cpp_plugin`).

**Comment by legeana** [comment]
Repository created: https://github.com/mesonbuild/grpc

I am not sure about the API of the wrap. Do you have any proposals?

**Comment by ricardoaiglesias** [comment]
I think a good starting point would be to 
1. Provide the ability to generate `libgrcpp` and any related libraries
2. Provide the related plugin executables. 

I'm not too familiar with the wrapping process, so I'm not sure how difficult this would be.

**Comment by kotx** [comment]
Any update on this?

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
