### ISSUE TITLE
new wrap: facil.io

### ISSUE THREAD

**Issue by zweimach** [mesonbuild/wrapdb#31]
upstream url: https://github.com/boazsegev/facil.io/tree/0.7.5
version: 0.7.5

**Comment by legeana** [comment]
The pkg-config file is called `facil.pc`, I am naming the repository `facil` as well according to our naming convention.
Please submit a pull request.

```
$ mesonwrap new_repo --homepage=facil.io --version=0.7.5 --directory ~/wrapdb/facil facil
```
Repository created: https://github.com/mesonbuild/facil
