### ISSUE TITLE
openssl wrap install fails

### ISSUE THREAD

**Issue by glimchb** [mesonbuild/wrapdb#320]
see https://github.com/linux-nvme/libnvme/issues/268
```
RuntimeError: File 'subprojects/openssl-1.1.1l/openssl' could not be found
```
from https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/openssl/meson.build
```
openssl_cli = executable(
  'openssl',
  build_by_default: false,
  dependencies: dependencies + [openssl_dep],
  sources: openssl_cli_sources,
  include_directories: include_directories,
  c_args: c_args,
  install: true,
)
```
what should happen if `build_by_default: false` and `install: true` is set. I haven't found anything related...

@nazar-pc @xclaesse @jpakkane any advice ?

**Comment by nazar-pc** [comment]
https://github.com/linux-nvme/libnvme/issues/268#issuecomment-1056508141 is relevant:
```
$ meson install -n -C .build
ninja: Entering directory `/home/wagi/work/nvme-cli/.build'
ninja: no work to do.
Installing subprojects/openssl-1.1.1l/libcrypto.so to /tmp/nvme-cli/lib64
Installing subprojects/openssl-1.1.1l/libssl.so to /tmp/nvme-cli/lib64

ERROR: File 'subprojects/openssl-1.1.1l/openssl' could not be found
```

It doesn't build executable, but tries to install it anyway. This doesn't make sense to me to be honest, maybe Meson should be smarter than that?

**Comment by glimchb** [comment]
@nazar-pc for ow can wrap-db workaround this somehow ?

**Comment by eli-schwartz** [comment]
IMHO those options are logically incompatible and if anything meson should error out and say "fix your meson.build, these options make no sense together".

If the intention is to not compile things which are not needed for a subproject, the general solution should be one of:
- compile it anyway, it likely doesn't take much time at all
- add a project option for whether to add it as a build target in the first place, and if enabled then have it both build by default and get installed

**Comment by glimchb** [comment]
@eli-schwartz I agree completely, 
but the problematic meson.build is defined in wrapdb here 
 https://wrapdb.mesonbuild.com/v2/openssl_1.1.1l-2/get_patch
see openssl-1.1.1l/meson.build
```
openssl_cli = executable(
  'openssl',
  build_by_default: false,
  dependencies: dependencies + [openssl_dep],
  sources: openssl_cli_sources,
  include_directories: include_directories,
  c_args: c_args,
  install: true,
)
```
how can we fix it ?

**Comment by eli-schwartz** [comment]
There is no "but" here. I'm quite aware that this is the WrapDB repository, i.e. the place to report bugs with `meson.build` files distributed by the wrapdb.

We can fix it by submitting a PR to this repository which implements one of the two options I described above. Then release a new version of the wrap.

**Comment by glimchb** [comment]
@eli-schwartz I can upload a patch, no problem. can you please help review and release new wrap? 
if you prefer submitting your own patch that's totally fine as well, let me know

**Comment by glimchb** [comment]
just found already opened PR https://github.com/mesonbuild/wrapdb/pull/297

**Comment by eli-schwartz** [comment]
That PR seems sub-optimal since it causes it to never be installed *and* never built by default.

The former means it is less useful as a basis for correctly implementing the build system in the hope of submitting it upstream.

The latter means it isn't tested in the WrapDB CI.

Maybe you can submit another PR, which implements one of the options I suggested instead?

**Comment by glimchb** [comment]
@eli-schwartz done https://github.com/mesonbuild/wrapdb/pull/322 please review
