### ISSUE TITLE
new wrap: unittest-cpp

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#36]
upstream url: 2.0.0
version: https://github.com/unittest-cpp/unittest-cpp/archive/v2.0.0.zip

**Comment by legeana** [comment]
Usually the naming convention is to use pkg-config filename as a package name, however in this case it's `UnitTest++`.

```
install(FILES       "${CMAKE_CURRENT_BINARY_DIR}/UnitTest++.pc"
        DESTINATION "${pkgconfdir}")
```

So let's go with the project name itself.

`$ mesonwrap new_repo --homepage=https://github.com/unittest-cpp/unittest-cpp --version=2.0.0 --directory ~/wrapdb/unittest-cpp unittest-cpp`
Repository created: https://github.com/mesonbuild/unittest-cpp
