### ISSUE TITLE
Is anyone working on Meson wrap definitions for "flac" "libmodplug" and so on?

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#38]
Is anyone working on Meson wrap definitions for the following? 

```console
libvorbisidec
mpg123
opus
opusfile
libmodplug
flac
```

Needed for the `sdl2_mixer` Meson build definition package. I was happy to find `ogg`, and `vorbis` were in the database.

**Comment by xhaakon** [comment]
I've requested a new wrap repository for opus: https://github.com/mesonbuild/wrapdb/issues/60

For now my wrap is hosted [here](https://github.com/xhaakon/opus-wrapdb) if you care to try it out.

**Comment by xhaakon** [comment]
Wrap repository for opus has been created. MR with 1.3.1 build files: https://github.com/mesonbuild/opus/pull/1

**Comment by michaelbrockus** [comment]
Fantastic @xhaakon just a few upstream packages away from `SDL2_mixer` to have true dependency management. I’m not sure if your family with the DodoWrap service but one of things I wish to enforce if possible is to define wrap packages that doesn’t depend on the user to have installed the dependency in the first place rather that the package manager Wrap in this case should do the heavy lifting on the user’s behalf. With the introduction of the provides section it makes it easier to list subprojects provided in the upstream package.

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
