### ISSUE TITLE
new wrap: libwebp

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#39]
upstream url: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0.tar.gz
version: 1.1.0

**Comment by legeana** [comment]
Does the project have an official homepage? I am struggling to find it.

**Comment by michaelbrockus** [comment]
I think this is it.

https://developers.google.com/speed/webp

**Comment by legeana** [comment]
$ mesonwrap new_repo --homepage=https://developers.google.com/speed/webp --version=1.1.0 --directory=~/wrapdb/libwebp libwebp
Repository created: https://github.com/mesonbuild/libwebp
