### ISSUE TITLE
SDL2 forces dependents to use SDL_main on Windows

### ISSUE THREAD

**Issue by AlpyneDreams** [mesonbuild/wrapdb#443]
The SDL2 meson wrap doesn't allow the project that's including it to disable linking the `sdl2main` library. This is problematic for appliactions that don't want to export `WinMain` such as non-graphical apps (where `win_subsystem` is `console`)  or apps that simply want to use the same main function for all platforms without including SDL headers. It also creates linker errors for me that I can't seem to work around.

Perhaps there should probably be an option checked [where use_sdl2main is set](https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/sdl2/meson.build#L1045), because currently it's always true on supported platforms.

**Comment by eli-schwartz** [comment]
@Jan200101
