### ISSUE TITLE
new wrap: doctest

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#45]
upstream url: https://github.com/onqtam/doctest/archive/2.4.0.zip
version: 2.4.0

**Comment by legeana** [comment]
$ mesonwrap new_repo --homepage=https://github.com/onqtam/doctest --version=2.4.0 --directory=~/wrapdb/doctest doctest
Repository created: https://github.com/mesonbuild/doctest

**Comment by legeana** [comment]
This was a duplicate, please see https://github.com/mesonbuild/onqtam-doctest
