### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by xclaesse** [mesonbuild/wrapdb#455]
Build All CI has been broken for a while, let's track here the failures:

- Linux:
  - libuv - https://github.com/mesonbuild/wrapdb/pull/367, `../../home/runner/work/wrapdb/wrapdb/subprojects/libuv-v1.44.1/include/uv/unix.h:136:9: error: unknown type name ‘pthread_rwlock_t’`

- MacOs:
  - sdl2 - `./../../../../../../Users/runner/work/wrapdb/wrapdb/subprojects/SDL2-2.0.20/src/core/linux/../../video/x11/SDL_x11sym.h:46:1: error: function cannot return function type 'int (Display *, Pixmap, Pixmap, XColor *, XColor *, unsigned int, unsigned int)' (aka 'int (struct _XDisplay *, unsigned long, unsigned long, XColor *, XColor *, unsigned int, unsigned int)')`

**Comment by neheb** [comment]
@xclaesse an alpine linux CI will catch more failures like the first. That's been my experience with OpenWrt which also uses musl.

**Comment by neheb** [comment]
https://github.com/mesonbuild/wrapdb/pull/459 should expose more.

**Comment by neheb** [comment]
Hmm not too bad:

```
417:FAILED: subprojects/box2d-2.4.1/unit-test/hello_world.p/hello_world.cpp.o
3193:FAILED: subprojects/libfuse-fuse-2.9.9/util/ulockmgr_server.p/ulockmgr_server.c.o
8578:FAILED: subprojects/libebml-release-1.4.2/liblibebml.a.p/src_EbmlString.cpp.o
8609:FAILED: subprojects/libebml-release-1.4.2/liblibebml.a.p/src_EbmlUnicodeString.cpp.o
8867:FAILED: subprojects/ffmpegthumbnailer-2.2.2/libffmpegthumbnailer.so.4.15.1.p/libffmpegthumbnailer_moviedecoder.cpp.o
19130:FAILED: subprojects/SDL2_image-2.0.5/libsdl2image.so
19840:FAILED: subprojects/SDL2_mixer-2.0.4/libsdl2mixer.so
20485:FAILED: subprojects/SDL2_net-2.0.1/libsdl2_net.so
21244:FAILED: subprojects/SDL2_ttf-2.0.12/libsdl2_ttf.so
```

**Comment by ninjaoflight** [comment]
#465 should fix the issue for hinnant-date in Windows.

**Comment by xclaesse** [comment]
Good, all Windows issues solved, remains only libuv on Linux and sdl2 on MacOS.

**Comment by xclaesse** [comment]
Update:
- Windows has many regressions: cmocka, emilk-loguru, fluidsynth, glib, json-c, json-glib, libexif, ludocode-mpack, m4, miniz, taglib, tinyply, utf8proc, yajl -> https://pipelines.actions.githubusercontent.com/serviceHosts/41920d4f-a01c-4531-8a4e-8f68e9dab867/_apis/pipelines/1/runs/2939/signedlogcontent/4?urlExpires=2022-08-26T14%3A15%3A44.0532725Z&urlSigningMethod=HMACV1&urlSignature=AxPjkoiRohcD%2BY8y8uWz1a7XgwClVoCsSoxsdii%2FTvA%3D
- macos only 2 failures: cmocka, sdl2 -> https://pipelines.actions.githubusercontent.com/serviceHosts/41920d4f-a01c-4531-8a4e-8f68e9dab867/_apis/pipelines/1/runs/2939/signedlogcontent/2?urlExpires=2022-08-26T14%3A15%3A48.2804501Z&urlSigningMethod=HMACV1&urlSignature=9%2B5n%2BoIiktk87CdcVvtJ%2Fc1dOoH3xocatFzzBDMYCUk%3D
- Linux only 2 failures: cmocka, libsndfile -> https://pipelines.actions.githubusercontent.com/serviceHosts/41920d4f-a01c-4531-8a4e-8f68e9dab867/_apis/pipelines/1/runs/2939/signedlogcontent/6?urlExpires=2022-08-26T14%3A15%3A16.3278689Z&urlSigningMethod=HMACV1&urlSignature=YXf05iy72BwMefxawJpuMbGRt3uouCElZwZDyeux0UA%3D

**Comment by xclaesse** [comment]
@Jan200101 sdl2 failed on macos, is that something you could look at please?

**Comment by xclaesse** [comment]
@neheb maybe failures on Windows seems to be a regression in pcre, is that something you could take a look please?
```
2022-08-26T12:25:49.5730169Z [201/1248] "link" @subprojects/glib-2.72.2/glib/glib-2.0-0.dll.rsp
2022-08-26T12:25:49.6089168Z FAILED: subprojects/glib-2.72.2/glib/glib-2.0-0.dll subprojects/glib-2.72.2/glib/glib-2.0-0.pdb 
2022-08-26T12:25:49.6090565Z "link" @subprojects/glib-2.72.2/glib/glib-2.0-0.dll.rsp
2022-08-26T12:25:49.6098525Z    Creating library subprojects\glib-2.72.2\glib\glib-2.0.lib and object subprojects\glib-2.72.2\glib\glib-2.0.exp
2022-08-26T12:25:49.6102304Z D__a_wrapdb_wrapdb_subprojects_glib-2.72.2_glib_gregex.c.obj : error LNK2001: unresolved external symbol pcre_free
2022-08-26T12:25:49.6105204Z subprojects\glib-2.72.2\glib\glib-2.0-0.dll : fatal error LNK1120: 1 unresolved externals
```

**Comment by xclaesse** [comment]
@neheb since you added libsndfile, could you look at its failure too please?

```
2022-08-26T12:36:29.1381558Z ../../home/runner/work/wrapdb/wrapdb/subprojects/libsndfile-1.1.0/programs/sndfile-play.c:677:17: error: storage size of ‘par’ isn’t known
2022-08-26T12:36:29.1381981Z   677 |  struct sio_par par ;
2022-08-26T12:36:29.1382259Z       |                 ^~~
```

**Comment by neheb** [comment]
libsndfile fixed by https://github.com/mesonbuild/wrapdb/pull/591

**Comment by xclaesse** [comment]
cmocka should be fixed by https://github.com/mesonbuild/wrapdb/pull/596

**Comment by Jan200101** [comment]
> @Jan200101 sdl2 failed on macos, is that something you could look at please?

I sadly don't have a MacOS machine to test on so I can mostly just theorize why this is happening.

```
/usr/local/Cellar/libxcursor/1.2.1/include/X11/Xcursor/Xcursor.h:207:5: error: unknown type name 'Cursor'
    Cursor          *cursors;   /* array of cursors */
    ^
```
Digging through the headers I can find that `X.h`, which `XCursor.h` includes over`Xlib.h` defines Cursor
to be
```c
typedef XID Cursor;
```
`X.h` is provided by xorgproto on Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/d5ea602d327021c0d2ec47e44ada1a39698bb5ec/Formula/xorgproto.rb)
`Xlib.h` is provded by libx11 on Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libx11.rb#L4)
`XCursor.h` is provided by libxcursor on Homebrew [formula] (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libxcursor.rb)

For some unknown reason this does not work anymore (though it previously worked for the PRs)

**Comment by neheb** [comment]
In an all wraps CI run, all brew packages listed in ci_config.json are available. So it's probably picking up extra ones.

**Comment by xclaesse** [comment]
I got bored at seeing build-all CI failing, so I made a PR to blacklist remaining issues. Help would be really appreciated to fix them!

https://github.com/mesonbuild/wrapdb/pull/611

**Comment by neheb** [comment]
@Jan200101 so I see this in the build all run:

```
2022-10-16T03:50:58.6571820Z sdl2| Run-time dependency x11 found: YES 1.8.1
2022-10-16T03:50:58.6572190Z sdl2| Run-time dependency xext found: YES 1.3.4
2022-10-16T03:50:58.6572540Z sdl2| Run-time dependency xi found: YES 1.8
2022-10-16T03:50:58.6572900Z sdl2| Run-time dependency xkbcommon found: YES 1.4.1
2022-10-16T03:50:58.6573340Z sdl2| Run-time dependency xrandr found: NO (tried pkgconfig, framework and cmake)
2022-10-16T03:50:58.6573740Z sdl2| Run-time dependency xfixes found: YES 6.0.0
2022-10-16T03:50:58.6574170Z sdl2| Run-time dependency xcursor found: NO (tried pkgconfig, framework and cmake)
```

xcursor seems to be used but it says not found. might make sense to force it if x11 is found.
