### ISSUE TITLE
glib fails on musl

### ISSUE THREAD

**Issue by neheb** [mesonbuild/wrapdb#469]
Alpine Linux has the following patch for it: https://git.alpinelinux.org/aports/tree/main/glib/musl-libintl.patch

Unfortunately, it breaks compilation elsewhere. I don't know of a good solution. There's a different hack used in OpenWrt as well...

**Comment by eli-schwartz** [comment]
This isn't a wrapdb problem, it's an upstream glib issue.

FWIW the general fix is `dependency('intl')`, and I tried submitting it here: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2685#note_1464884

"It's complicated."

**Comment by xclaesse** [comment]
@eli-schwartz if your patch actually fix issue for alpine and openwrt, I think you should resubmit it to glib. Seems to be more than a cleanup. 

@neheb do you have a link to openwrt issue or patch?

**Comment by neheb** [comment]
I maintain the OpenWrt one. Both OpenWrt and Alpine use musl.

The OpenWrt patch is https://github.com/openwrt/packages/blob/master/libs/glib2/patches/007-openwrt-libintl.patch . It's a hack based on the way glib is setup on OpenWrt. I doubt upstream would accept.

**Comment by xclaesse** [comment]
@neheb OOC, what's the problem with musl ngettext implementation? Why are you forcing using libintl?

**Comment by neheb** [comment]
musl has a libintl header but does not really implement it.

**Comment by xclaesse** [comment]
Oh, similar to what @eli-schwartz explained there for iconv: https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2685#note_1462925. Meson indeed does a better test by trying to link a sample code instead of relying on `cc.has_function('ngettext')` that only does a compile but not link.

**Comment by eli-schwartz** [comment]
> @neheb OOC, what's the problem with musl ngettext implementation? Why are you forcing using libintl?

The general rule for intl/iconv is that even on systems where some version of it exists already, installing the GNU one will get you a much more capable version. This is also why GNU libiconv is often selected to be used on BSD systems, despite it being a POSIX requirement and implemented in their libc.

**Comment by neheb** [comment]
> > I maintain the OpenWrt one. Both OpenWrt and Alpine use musl.
> > The OpenWrt patch is https://github.com/openwrt/packages/blob/master/libs/glib2/patches/007-openwrt-libintl.patch . It's a hack based on the way glib is setup on OpenWrt. I doubt upstream would accept.
> 
> FYI, even if NLS is disabled, GLib will still need to link to libintl API. The NLS option is only used to disable generating PO files using xgettext.

Right. Although when NLS is disabled, the libc gettext support is enough.

More info on this mess: https://github.com/openwrt/packages/pull/18688

**Comment by xclaesse** [comment]
@neheb Would like to have your feedback on https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2734. Could you give it a quick test on Alpine and OpenWRT please? With that, do you still need downstream patching?

**Comment by neheb** [comment]
@xclaesse discussing on IRC. Almost perfect. I posted on https://github.com/openwrt/packages/pull/18712 to see if there are any issues.

**Comment by neheb** [comment]
@xclaesse seems the intl issue is gone now. will be doing a CONFIG_ALL compilation test to see if any other problems.
