### ISSUE TITLE
new wrap for doctest

### ISSUE THREAD

**Issue by asartori86** [mesonbuild/wrapdb#5]
upstream url: https://github.com/onqtam/doctest
version: 2.3.7

**Comment by legeana** [comment]
This can be confused with a very popular Python module: https://en.wikipedia.org/wiki/Doctest
What do you think about `onqtam-doctest`?

**Comment by asartori86** [comment]
Thanks, @legeana. `doctest-cpp`? Otherwise what you propose is fine as well :)

**Comment by legeana** [comment]
It's not the official name though.
I created https://github.com/mesonbuild/onqtam-doctest.
