### ISSUE TITLE
cjson test fails under clang32 MSYS2 backend

### ISSUE THREAD

**Issue by neheb** [mesonbuild/wrapdb#513]
https://gist.github.com/neheb/a23993b43a6ca3f97e7ea368a4cda486

I can't tell if this is an MSYS2 or meson bug.

ping @lazka

**Comment by neheb** [comment]
I assume this is a Windows issue.

**Comment by lazka** [comment]
It's because one test is called "json_patch_tests" and Windows auto elevates 32bit .exe files which contain things like "auto"/"setup"/"patch".

**Comment by neheb** [comment]
that's...quite the behavior.

**Comment by lazka** [comment]
yeah, afair you can prevent it by embedding a manifest that forces it off.

**Comment by lazka** [comment]
huh, though it is weird that this is clang specific

**Comment by neheb** [comment]
yeah I don't remember MinGW32 doing this.
