### ISSUE TITLE
new wrap: genann

### ISSUE THREAD

**Issue by michaelbrockus** [mesonbuild/wrapdb#54]
upstream url: https://github.com/codeplea/genann/releases/tag/v1.0.0
project url: https://github.com/codeplea/genann
version: 1.0.0

**Comment by legeana** [comment]
$ mesonwrap new_repo --homepage=https://github.com/codeplea/genann --version=1.0.0 --directory=~/wrapdb/genann genann
Repository created: https://github.com/mesonbuild/genann
