### ISSUE TITLE
Question: Wrapping repos without versioning

### ISSUE THREAD

**Issue by tmayoff** [mesonbuild/wrapdb#549]
Not sure where to ask this but here goes. I want to add this repo to the wrapdb [freetype-gl](https://github.com/rougier/freetype-gl) but it doesn't version the library. Is there a way to deal with this solely in the wrapdb or do I need to have the author setup versioning upstream?

**Comment by dcbaker** [comment]
Usually we handle this by dating the snapshot, though it would be great if upstream has a versioning scheme

**Comment by tmayoff** [comment]
Thanks, I'll bring it up with upstream. Also small other question, I already setup and created the patch using a versioned fork, and when I tried to run the sanity checks it started cloning all of the projects. I feel like this wasn't the case for the last wrap I submitted did something change, or did I do something wrong? Is there a way to just sanity check the project I added?
