### ISSUE TITLE
Request: libcurl

### ISSUE THREAD

**Issue by pvonmoradi** [mesonbuild/wrapdb#561]
Please consider adding libcurl (in a way that can be built for windows from linux (cross-platform)).
Thanks

**Comment by tristan957** [comment]
@pvonmoradi have you tried the external project module? I use it for libcurl in my project, and I would be happy to share what I have written. Though, libcurl using Meson would definitely be better.

**Comment by pvonmoradi** [comment]
@tristan957 I use it like `curl_dep = dependency('libcurl')` (it needs `libcurl` to be installed on system). This works for linux but I don't think I can cross-compile to Windows with this. 

I'm not blocked by this issue though. So feel free to close it if adding it is too much work.

**Comment by tristan957** [comment]
Check this out: https://github.com/hse-project/hse/blob/master/subprojects/packagefiles/curl/meson.build

**Comment by eli-schwartz** [comment]
It's on my bucket list to port libcurl anyway.

I even got far enough to define meson_options.txt for it ;) but `-ENOTIME`.

Upstream's cmake is officially a mess though, so they might welcome a Meson port...

**Comment by tristan957** [comment]
Do they even have plans to drop autotools?

**Comment by ninjaoflight** [comment]
As a workaround you could install curl using vcpkg so you don´t have any issues with the windows build, I did that with some test projects
