### ISSUE TITLE
new wrap: trompeloeil

### ISSUE THREAD

**Issue by nawordar** [mesonbuild/wrapdb#57]
upstream url: https://github.com/rollbear/trompeloeil/archive/v38.zip
version: v38

**Comment by nawordar** [comment]
Would it be better to set version as 'v38' or '38' in meson.build?

**Comment by legeana** [comment]
38 is better, yes, for consistency.
$ mesonwrap new_repo --homepage=https://github.com/rollbear/trompeloeil --version=38 --directory=~/wrapdb/trompeloeil trompeloeil
Repository created: https://github.com/mesonbuild/trompeloeil
