### ISSUE TITLE
new wrap: libcuckoo

### ISSUE THREAD

**Issue by fischerling** [mesonbuild/wrapdb#59]
upstream url: [https://github.com/efficient/libcuckoo](https://github.com/efficient/libcuckoo)
version: 0.3

**Comment by fischerling** [comment]
This seems not very important because I managed to include libcuckoo into my meson project using it as a cmake module.

I have the wrap file `libcuckoo.wrap` in my subprojects directory:

	[wrap-git]
	url = https://github.com/efficient/libcuckoo
	revision = v0.3

and used in in my meson.build with this code:

	cmake = import('cmake')
	libcuckoo_proj = cmake.subproject('libcuckoo')
	libcuckoo_dep = libcuckoo_proj.dependency('libcuckoo')

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
