### ISSUE TITLE
new wrap stb libraries

### ISSUE THREAD

**Issue by RazrFalcon** [mesonbuild/wrapdb#6]
upstream url:  https://github.com/nothings/stb

`stb_truetype.h` specifically.

**Comment by legeana** [comment]
github.com/mesonbuild/stb

**Comment by RazrFalcon** [comment]
Thanks! Should I wait for a build server to finish or something? Right now `meson wrap install stb` returns 404.

**Comment by legeana** [comment]
Hi, the expectation is that the user will provide a wrap for it.
https://mesonbuild.com/Adding-new-projects-to-wrapdb.html#add-a-new-wrap

**Comment by RazrFalcon** [comment]
Oh, I should have read the docs to the end... Will try to figure it out.

**Comment by RazrFalcon** [comment]
stb is a collection of libraries where all of them have their own versions. How exactly it should be *wrapped*? Should we have a repo per library? Or multiple `meson.build`'s? Or else?

**Comment by legeana** [comment]
Probably it would be reasonable to have a single wrap for a repository. Say a user wants to use 3 libraries from stb, it would be unexpected to download the project 3 times.

**Comment by RazrFalcon** [comment]
But what version should we use in the wrap then?

**Comment by legeana** [comment]
Head might work. https://github.com/mesonbuild/meson/blob/master/docs/markdown/Wrap-dependency-system-manual.md#wrap-format gives an example.
