### ISSUE TITLE
Feature(fmt.wrap): build static library, offer it as a dep

### ISSUE THREAD

**Issue by kevr** [mesonbuild/wrapdb#606]
Current meson.build: https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/fmt/meson.build

This subproject offers a `library`, which is great. Is there a possibility that we could add a static_library to the fmt meson.build? I'd love to be able to build the dependency and compile statically within my own project.

The dependency requirement is a bit hard to deal with at the moment:

1. Fetch fmt.wrap and build it
2. Build your own project which depends on the fmt.wrap subproject
3. Install your project

Is the standard route for building through meson and installing to a system. With the way that fmt only builds a shared library, this also requires that we install fmt of the same exact version to dyn library resolution paths on a system that wishes to run your project.

This is an issue on Linux distributions because:
- Many linux distributions come with a version of `fmt` which is installed to the system
- People do not typically want to install `.so` dependencies along with a project which depend on them, because it would be breaking the "one job" mentality

So.. having a static library version of `fmt.wrap` that allows us to build without depending on an external `.so` would be much more stable and work in more places than the `.so`-only solution does.

Of course, this would add more overhead to the build process, as fmt's meson.build would then be responsible for building two different libraries: dynamic _and_ static.

I wonder if there's a way we could specify to the wrap which exact type we want? Perhaps this would better belong in a separate wrap like `fmt-static.wrap` or something?

**Comment by eli-schwartz** [comment]
> I wonder if there's a way we could specify to the wrap which exact type we want?

Indeed you can. :)

It can be overridden by the built-in option `default_library=static`, which can be defined various ways:
- for the main project, on the command line as `-Ddefault_library=static`
- for the subproject, on the command line as `-Ddefault_library=static`

It can also be set as a default in meson.build (which only applies when doing a clean `meson setup`) by specifying the option as default options:

`default_options: ['default_library=static']` applied as a kwarg to:
- `project()` -- the current project
- `subproject()` -- set in the current project to influence the other subproject 
- `dependency()` -- set in the current project to influence the other subproject, *iff* subproject fallback is performed

**Comment by kevr** [comment]
HA. Okay, that's much better. RTFM, kevr.

Thanks, eli.

**Comment by eli-schwartz** [comment]
> Of course, this would add more overhead to the build process, as fmt's meson.build would then be responsible for building two different libraries: dynamic *and* static.

Note that Meson's library handling has been carefully designed to optimize for user choice here. By default libraries are built shared, but there's three modes: shared, static, and both. Unless a project specifically insists that only one mode will work by e.g. using `shared_library()`, it all remains fully under the end user's control (and as stated in the previous comment, that control is granular at the per-subproject level).
