### ISSUE TITLE
new wrap: stb

### ISSUE THREAD

**Issue by noah1510** [mesonbuild/wrapdb#61]
because the stb developer does not want a meson.build file upstream here is a simple warp which downloads the latest version of stb using git and includes the dependency.
`dependency('stb', required : true, fallback : ['stb', 'stb_dep'])` is enough to use it.

```
[wrap-git]
url = https://github.com/noah1510/stb-meson.git
revision = main

[provides]
dependency_names = stb
stb=stb_dep
```

**Comment by noah1510** [comment]
at the moment the repo will always be deleted, feel free to create a pull request to optimize the behaviour

**Comment by jpakkane** [comment]
As a matter of policy, wrapdb only has releases. If upstream does not want to do releases, it can't be added to wrapdb. Sorry.

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
