### ISSUE TITLE
Add web API to query for provides

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/wrapdb#63]
As more wraps are starting to come with `[provide]` entries it would be nice to provide a web API for querying them. The use case would go something like this:

- This project uses dependency `foobaz`, what package would provide it?
- `meson wrap provides foobaz`
- the return value says it comes from wrap `libfoobaz`
- install and download as usually

**Comment by jcaesar** [comment]
Any plans to eventually take this a step further and add something like `meson wrap resolve-all` which could look for all dependencies that do not have a wrap, transitively:
```
Found the following wrap files:
 [1] foobaz v1.2 (required by root project)
 [2] blubb v636.0.1 (required by: foobaz)
 [3] hoge v0.42 (required by: blubb, foobaz)
Enter the numbers of wrap files you'd like to keep, or "all": _
```

**Comment by xclaesse** [comment]
This information is now avaible in json format with the URL https://wrapdb.mesonbuild.com/v2/releases.json
