### ISSUE TITLE
new wrap: termbox

### ISSUE THREAD

**Issue by pkitszel** [mesonbuild/wrapdb#64]
upstream url: https://github.com/nsf/termbox
version: 1.1.2

I started using meson yesterday, but already really like it.

I just wonder if it would be easier to maintain wrapdb if contributors would just submit PRs instead of issue + wait-for-repo + PR combo?

**Comment by jpakkane** [comment]
> I just wonder if it would be easier to maintain wrapdb if contributors would just submit PRs instead of issue + wait-for-repo + PR combo?

After the repo has been created, that is all you have to do. Repos can not be created automatically but instead require human intervention to block spammers and the like. For this particular library, their readme explicitly says that it is no longer maintained and that people should use forks instead. Is there one?

**Comment by pkitszel** [comment]
Ad. repo/PRs: Current flow is indeed convenient for contributors, I just wonder if it would be easier for maintainers to create repo only after looking at actual PR (even if such PR should be rebased in new repo). In such scenario, there would be no effort if someone just _wants_ to have some project, but then will lose interest or be unable to properly implement meson.build for given library.

Regarding *termbox*, project is indeed kept as-is, but on other hand functionality could be considered done.

There were even unagreements between author and community about what should be added into the lib.

Would you prefer to base wrap on most promising fork (whatever it would be in this case)? If so, we could advertise/keep version 1.1.2 for some users and _latest_ for others.

This already got long, so feel free to point better place for following questions ;)

Q1: is `configure_file(copy: true, input: 'src/termbox.h', output: 'termbox.h')` best way to export this include file, but no other files from _src_ dir?

Q2: what is best place to publish libraries that are built with meson (so they could be easily added as subprojects)?

**Comment by jpakkane** [comment]
Repo created.

> Q1: is configure_file(copy: true, input: 'src/termbox.h', output: 'termbox.h') best way to export this include file, but no other files from src dir?

If upstream has put it among private sources, sadly yes.

> Q2: what is best place to publish libraries that are built with meson (so they could be easily added as subprojects)?

Wrapdb can also take libraries that build with Meson. The "patch" file is just then empty. This is the recommended way.
