### ISSUE TITLE
SDL2 errors

### ISSUE THREAD

**Issue by neheb** [mesonbuild/wrapdb#676]
Does not compile on MinGW:

https://gist.github.com/neheb/a2e3ada37e7d9fbb8bbf1d1e4871eb3a

Fails muon analyze. The issue is cc being used before being defined. Fixed with this patch:

```
--- a/subprojects/packagefiles/sdl2/meson.build
+++ b/subprojects/packagefiles/sdl2/meson.build
@@ -1,11 +1,13 @@
 project('sdl2', 'c',
     version : '2.24.0',
     license : 'zlib',
-    meson_version : '>=0.48.0',
+    meson_version : '>=0.49.0',
     default_options : ['c_std=none'],
 )

-if get_option('default_library') == 'both' and cc.get_id() == 'msvc'
+cc = meson.get_compiler('c')
+
+if get_option('default_library') == 'both' and cc.get_argument_syntax() == 'msvc'
   error('default_library=both not supported when compiling with MSVC')
 endif

@@ -16,8 +18,6 @@ version_major = varr[0]
 version_minor = varr[1]
 version_micro = varr[2]

-cc = meson.get_compiler('c')
-
 c_args = cc.get_supported_arguments(
     '-Wdeclaration-after-statement',
     '-Wshadow',
```

There's also a new version out. ping @Jan200101

**Comment by xclaesse** [comment]
I don't think that part is true :  `cc.get_argument_syntax() == 'msvc'`. Building both is never supported for Windows, whatever the compiler.

**Comment by Jan200101** [comment]
Its always fun to see MinGW and MSVC disagree on everything.
I'll throw MXE at it later and try to fix this.

> I don't think that part is true : `cc.get_argument_syntax() == 'msvc'`. Building both is never supported for Windows, whatever the compiler.

Shouldn't the check then be `get_option('default_library') == 'both' and host_machine.system() == 'windows'` ?

**Comment by xclaesse** [comment]
Hold a minute, I'm not entirely sure about this actually. I recently discovered that GLib does this completely wrong, and GStreamer does it only for MSVC too. It seems nobody really knows... We should sort out this mess once and for all in https://github.com/mesonbuild/meson/pull/10199 IMHO.

@neheb in any case, that's unrelated to the issue you found, please make a PR.

**Comment by neheb** [comment]
still errors:

```
FAILED: subprojects/SDL2-2.24.0/test/testgles2.exe.p/testgles2.c.obj
x86_64-w64-mingw32-gcc -Isubprojects/SDL2-2.24.0/test/testgles2.exe.p -Isubprojects/SDL2-2.24.0/test -I../subprojects/SDL2-2.24.0/test -Isubprojects/SDL2-2.24.0/include -I../subprojects/SDL2-2.24.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -Wdeclaration-after-statement -Wshadow -fno-strict-aliasing -Wdeclaration-after-statement -Wshadow -fno-strict-aliasing -MD -MQ subprojects/SDL2-2.24.0/test/testgles2.exe.p/testgles2.c.obj -MF subprojects/SDL2-2.24.0/test/testgles2.exe.p/testgles2.c.obj.d -o subprojects/SDL2-2.24.0/test/testgles2.exe.p/testgles2.c.obj -c ../subprojects/SDL2-2.24.0/test/testgles2.c
In file included from ../subprojects/SDL2-2.24.0/test/testgles2.c:32:
subprojects/SDL2-2.24.0/include/SDL_opengles2.h:35:10: fatal error: GLES2/gl2platform.h: No such file or directory
   35 | #include <GLES2/gl2platform.h>
```

as well as all the linkers errors that I posted previously.

**Comment by Jan200101** [comment]
That is odd.

https://github.com/mesonbuild/wrapdb/blob/93650ec9379ca401ea6173cd5fd2a5ec7f5990de/subprojects/packagefiles/sdl2/meson.build#L1075 should be setting this.

I can't recreate this using MXE, what release of MinGW are you using?
How are you compiling this wrap (crossfile, env flags, etc.)?
meson could also be the cause of this since I am still using 0.62.2.

**Comment by neheb** [comment]
```
[binaries]
c = 'x86_64-w64-mingw32-gcc'
cpp = 'x86_64-w64-mingw32-g++'
ld = 'x86_64-w64-mingw32-ld'
ar = 'x86_64-w64-mingw32-ar'
dlltool = 'x86_64-w64-mingw32-dlltool'
strip = 'x86_64-w64-mingw32-strip'
pkgconfig = 'x86_64-w64-mingw32-pkg-config'
windres = 'x86_64-w64-mingw32-windres'
rcc = '/usr/x86_64-w64-mingw32/bin/qt5/rcc'
moc = '/usr/x86_64-w64-mingw32/bin/qt5/moc'
uic = '/usr/x86_64-w64-mingw32/bin/qt5/uic'
exe_wrapper = 'wine64'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'
```

MinGW is fedora's version.

**Comment by Jan200101** [comment]
Installed Fedoras MinGW and figured out where my issue was:
the MinGW I compiled with MXE was entirely static and this issue is caused by SDL2main being linked into the SDL2 dynamic librarym causing an undefined reference.

The fix is as simple as moving the `deps += sdl2main_dep` under `sdl2` so it only becomes a dependency of dependency object
