### ISSUE TITLE
SDL2 failure under MinGW

### ISSUE THREAD

**Issue by neheb** [mesonbuild/wrapdb#766]
ping @Jan200101

https://gist.github.com/neheb/0a5927a546027f0417a243db63d9005e

Sounds like a missing dependency.

**Comment by Jan200101** [comment]
I can't figure out a way to reproduce this.

the pulseaudio code is only used when its available at compile time so it does not appear to be a missing dependency.
`pa_strerror` has existed for a pretty long while and is widely used so its not something they added recently.

I suspect that the Windows port of pulseaudio is simply busted.

**Comment by neheb** [comment]
yeah this is related to https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/761

Closing.
