### ISSUE TITLE
new wrap: reflex

### ISSUE THREAD

**Issue by dnicolodi** [mesonbuild/wrapdb#78]
upstream url: https://github.com/Genivia/RE-flex
version: 3.0.1

Please note that the project naming is a bit confusing: in the documentation the software is called RE/flex, however, the git repository is called RE-flex as the published release tarballs, however, the installer binary is named `reflex` and the associated library `libreflex`. I think `reflex` is the appropriate name for the wrap.

**Comment by jpakkane** [comment]
Repo created.
