### ISSUE TITLE
new wrap: sqlite3

### ISSUE THREAD

**Issue by jkuebart** [mesonbuild/wrapdb#80]
upstream url: https://www.sqlite.org/2020/sqlite-amalgamation-3340000.zip
version: 3.34

**Comment by jkuebart** [comment]
I think the existing `sqlite` wrap has two problems:
* Name: conventionally, SQLite is available from `pkg-config` as `sqlite3`, see for example Homebrew.
* Version: conventionally, the proper version number such as 3.34 is used for packages.

As such, trying to use the current `sqlite` wrap as a fallback fails because the names don't match and it's impossible to use a version range. I think it's convenient to have a wrap that can be used as
```
        dependency('sqlite3', version: ['>=3.28', '<4']),
```

**Comment by jpakkane** [comment]
i have pushed a fix with a provide entry. It has the correct name so

```meson
sqlite_dep = dependency('sqlite3')
```

should work. The version numbering is a bit wonky as the naming scheme is a bit odd.

This is not to say we could not create a 'sqlite3` entry as well. It just gets a bit confusing to have two (and we need to keep the old ones for bw compatibility).

**Comment by jkuebart** [comment]
@jpakkane thanks Jussi that's definitely already a good improvement. It's unfortunate that the versions were chosen as they were and I agree that due to compatibility the old one would need to remain available. Is there a way to add some documentation to explain the differences to users (or perhaps mark one as deprecated) if there was new `sqlite3` wrap?

**Comment by polesapart** [comment]
I suggest keeping the old name unmaintained and use sqlite3 with the new version notation, i.e. deprecate the previous sqlite entry and don't bind the sqlite3 to that odd versioning scheme. So legacy projects will continue to build, and if whoever depends on it requires an updated sqlite, they'll have to migrate (in most cases this will be a single-line change on meson).

**Comment by jkuebart** [comment]
@polesapart I'm happy to provide what I use if and when the repo is created. See
https://gitlab.com/jkuebart/wa2html/-/blob/main/external/sqlite3.wrap
https://gitlab.com/jkuebart/wa2html/-/blob/main/external/packagefiles/sqlite3/meson.build

**Comment by jpakkane** [comment]
I can create the new repo, which version number should the release have?

**Comment by jkuebart** [comment]
the current version is `sqlite3-3.34.1`.
