### ISSUE TITLE
ffmpeg needed

### ISSUE THREAD

**Issue by walkthunder** [mesonbuild/wrapdb#82]
Need ffmpeg for my cases. Hope for it. Thx

**Comment by tp-m** [comment]
There's a meson port here: https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg

Wrap file: https://gitlab.freedesktop.org/gstreamer/gst-build/-/blob/master/subprojects/FFmpeg.wrap

**Comment by jpakkane** [comment]
If you are willing to help get it done, I can create the repo.

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
