### ISSUE TITLE
new wrap: libexif

### ISSUE THREAD

**Issue by AngeloFrangione** [mesonbuild/wrapdb#85]
upstream url: https://github.com/libexif/libexif
version: 0.6.22

**Comment by jpakkane** [comment]
Repo created, please file a pr with your files: https://github.com/mesonbuild/libexif

Thanks,

**Comment by AngeloFrangione** [comment]
Oh sorry I thought it was for requesting a wrap that doesn't exists. 

Guess I need to do the meson build file for it then ?

**Comment by jpakkane** [comment]
Yes. All build files are contributed by the community, we don't have the resources to create them ourselves, sadly.

**Comment by AngeloFrangione** [comment]
Okay, I will do it then, hope I figure it out because I'm fairly new with the meson build system, do you have some great resources I can look into to make a great meson build file for the community that works correctly ? 

Or if I manage to make it work for me it should work for everyone?

**Comment by jpakkane** [comment]
Once you submit what you have it will go through review and you'll get comments on how proceed from there. Many of wraps of this type are basically just "do minimal configuration, build a single library with `library()` and define a dependency object".
