### ISSUE TITLE
new wrap: libmagic

### ISSUE THREAD

**Issue by AngeloFrangione** [mesonbuild/wrapdb#86]
upstream url: https://github.com/file/file
version: FILE5_39

**Comment by jpakkane** [comment]
Do you plan to port this as well?

For the record the URL should be http://www.darwinsys.com/file/ and the version should be 5.39 to match the actual releases rather than the weird numbering that the Git mirror has.

**Comment by AngeloFrangione** [comment]
It stopped working on it it's too time consuming for something that does not work really on windows.

**Comment by jpakkane** [comment]
It's fine to add a wrap entry that only works on Linux, say. It is already useful. If people need it to work on other platforms they will submit patches.

**Comment by AngeloFrangione** [comment]
Okay, I will remember it next time I try to make a wrap, but I think I don't have this one anymore :/

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.
