### ISSUE TITLE
request: libsndfile

### ISSUE THREAD

**Issue by alex-tee** [mesonbuild/wrapdb#87]

**Comment by jpakkane** [comment]
Do you have a port of the build system ready or are you merely requesting someone else to do the port?

If it is the latter, then unfortunately the wrapdb people do not have resources to spend on porting projects. However if you submit your own, adding it should be fairly straightforward.

**Comment by alex-tee** [comment]
I don't have a port yet but I'll see if I can do it

question: are cmake-based or autotools-based wraps acceptable or does the build system need to be ported to meson completely?

**Comment by jpakkane** [comment]
It needs to be Meson. If people want to build it with other build systems they can use `unstable_external_project`.

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.

**Comment by neheb** [comment]
libsndfile is now in master.
