### ISSUE TITLE
Add workarounds for `configure_file(copy: true)`

### ISSUE THREAD

**Issue by tristan957** [mesonbuild/wrapdb#887]
I was using Meson master today. I saw the following while using the `cjson` wrap.

```
cjson| NOTICE: Future-deprecated features used:
cjson| * 0.64.0: {'copy arg in configure_file'}
```

While not a huge deal, it probably makes sense to pre-emptively try to change all uses in the wrapdb to use `fs.copyfile()` based on the Meson version.

**Comment by eli-schwartz** [comment]
I've considered once or twice removing the "future-deprecated features" notice for precisely this reason, and making it only print when specifically asking for it via a CLI flag...

**Comment by tristan957** [comment]
https://github.com/search?q=repo%3Amesonbuild%2Fwrapdb+%22copy%3A+true%22&type=code seems to say there are only 20 uses, so should be a quick PR that I can probably get to tonight.

**Comment by eli-schwartz** [comment]
It's explicitly not a warning and doesn't hamper CI. --fatal-meson-warnings doesn't trigger on it.

What will trigger is if the minimum version is raised due to adding new features to the meson.build, and at that time you'd need to migrate the deprecated functions.

Or drop outdated else clauses.

**Comment by tristan957** [comment]
Yes, I am aware of that. I just want to be prepared for when I update some of my minimum versions :), so if I do it for one wrap, I might as well just do it for all.

**Comment by tristan957** [comment]
Ah you mean the subprojects update their minimum meson versions, not the parent projects. Whoops.
