### ISSUE TITLE
new wrap: TCLAP

### ISSUE THREAD

**Issue by ManuelAtWork** [mesonbuild/wrapdb#89]
upstream url: https://sourceforge.net/projects/tclap/files/tclap-1.2.1.tar.gz
version: 1.2.1

**Comment by jpakkane** [comment]
Do you have a port of the build system ready or are you merely requesting someone else to do the port?

If it is the latter, then unfortunately the wrapdb people do not have resources to spend on porting projects. However if you submit your own, adding it should be fairly straightforward.

**Comment by ManuelAtWork** [comment]
I have the wrap and the patch - including unit tests - ready to go. (It works on my system, conforms to all review criteria and has been tested with some cross-builds.)

This is my first wrap submittal. If it goes well, I would be willing to submit additional wraps for other versions or other projects.

**Comment by jpakkane** [comment]
Great, repo created. Thanks.
