### ISSUE TITLE
new wrap : nonius

### ISSUE THREAD

**Issue by edmeme** [mesonbuild/wrapdb#9]
upstream url: https://github.com/edmeme/nonius
nonius
version: 1.1.2

**Comment by legeana** [comment]
As I understood https://github.com/libnonius/nonius is the actual upstream.
https://github.com/mesonbuild/nonius is up.

**Comment by edmeme** [comment]
It is, thanks!

**Comment by legeana** [comment]
Could you please make a pull request?
