### ISSUE TITLE
Adding OpenSSL v1 entry?

### ISSUE THREAD

**Issue by amyspark** [mesonbuild/wrapdb#900]
Hey all,

This is a survey issue to see if the Meson project would be interested in adding OpenSSL 1.x back. We at Krita could use the centralized wrap, and I've had a similar request from the GStreamer developers.

See https://gitlab.freedesktop.org/gstreamer/cerbero/-/issues/215

cc @nirbheek @tp-m

**Comment by xclaesse** [comment]
Why not porting GST to v3?

**Comment by eli-schwartz** [comment]
Old versions of existing wraps do remain available and can be manually downloaded from https://wrapdb.mesonbuild.com

But in this case, there's an actual maintained LTS branch (and that is 6 releases ahead of the last 1.x release we had here), so I can definitely see the argument in favor of it... hmm.

I think my main concern is that I'm not sure Meson handles multiple wraps providing the same dependency.

**Comment by amyspark** [comment]
@eli-schwartz I'm ok with renaming it to, say, `openssl-1` so that only users who opt in can use it.

**Comment by xclaesse** [comment]
> I think my main concern is that I'm not sure Meson handles multiple wraps providing the same dependency.

You need to include the version in the dependency name I'm that case.

**Comment by dvrogozh** [comment]
Mind that OpenSSL 1.1.1 series will be EOL in few months at 11th September 2023, see https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/.

**Comment by amyspark** [comment]
Closing due to the EOL warning.
