### ISSUE TITLE
new wrap: notcurses

### ISSUE THREAD

**Issue by DrBluefall** [mesonbuild/wrapdb#91]
upstream url: https://github.com/dankamongmen/notcurses
version: v2.2.3

**Comment by jpakkane** [comment]
Just to be sure, do you already have the build files ready to submit? Wrapdb maintainers have limited resources and sadly can't spend time actually porting build definitions.

**Comment by DrBluefall** [comment]
Yep, all the build files are written.

**Comment by jpakkane** [comment]
Great, repo created.
