### ISSUE TITLE
request: json-schema-validator

### ISSUE THREAD

**Issue by gutrix** [mesonbuild/wrapdb#93]
This would pair nicely with the already available nlohmann/json

**Comment by xclaesse** [comment]
New wraps can now be submitted directly as a Pull Request on this repository. See the updated [README](https://github.com/mesonbuild/wrapdb#readme) for the procedure.

**Comment by Tachi107** [comment]
@xclaesse so is the [documentation on mesonbuild.com](https://mesonbuild.com/Adding-new-projects-to-wrapdb.html) out of date?

**Comment by xclaesse** [comment]
Yes, it needs update, it's a work in progress: https://github.com/mesonbuild/meson/pull/8796
