### ISSUE TITLE
Wayland fails to cross compile with wrap subprojects

### ISSUE THREAD

**Issue by shrkamat** [mesonbuild/wrapdb#940]
I see Wayland fails to cross-compile compile for aarch64. I have created a minimal reproducible example  and shared [here](https://github.com/shrkamat/waystack)

##### Build steps
```
sudo apt-get install g++-aarch64-linux-gnu

git clone https://github.com/shrkamat/waystack.git
cd waystack
export WLD=$HOME/wld

meson subprojects download

(cd subprojects/wayland-1.20.0 && meson setup build -Dlibraries=false -Dtests=false -Ddtd_validation=false --prefix=$WLD/host_dep && ninja -C build install)
export PKG_CONFIG_PATH=$WLD/host_dep/lib/x86_64-linux-gnu/pkgconfig

meson setup build --prefix=$WLD --cross-file aarch64-linux-gnu.txt -Dwayland:documentation=false
```

Complete set of logs are shared [here](https://github.com/shrkamat/waystack/blob/master/logs/meson-log.txt#L3465)

Note `wayland-scanner` 1.18.0 is ubuntu host version and newly built binary is made available at `$WLD/host_deps` with pkg-config I see it's easily accessible.
  
```
skamath@thinkpad:~$ /usr/bin/pkg-config --modversion wayland-scanner
1.18.0
skamath@thinkpad:~$ PKG_CONFIG_PATH=$WLD/host_dep/lib/x86_64-linux-gnu/pkgconfig /usr/bin/pkg-config --modversion wayland-scanner
1.20.0
```

##### Env
```
meson --version
1.0.1

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by xclaesse** [comment]
wayland-scanner ans libwayland must exact same version.

**Comment by shrkamat** [comment]
Since with pkg-config meson is not able to find right version of `wayland-scanner` it seems like meson bug. More likely wrap script big.

**Comment by xclaesse** [comment]
It is intentional from Wayland upstream to require you have the same version installed on build machine when you cross build, there is nothing meson can do about it.

https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/src/meson.build#L81

**Comment by shrkamat** [comment]
Agreed, that is the reason why I have two builds, one for host and one for aarch64

```
# build wayland alone for host, install it to $WLD/host-deps
(cd subprojects/wayland-1.20.0 
     && meson setup build -Dlibraries=false -Dtests=false -Ddtd_validation=false --prefix=$WLD/host_dep 
     && ninja -C build install)

# export host install pkg-config path
export PKG_CONFIG_PATH=$WLD/host_dep/lib/x86_64-linux-gnu/pkgconfig

# build wayland along with other prerequisites for aarch64 (this fails during configure step)
meson setup build --prefix=$WLD --cross-file aarch64-linux-gnu.txt -Dwayland:documentation=false  
```

my exact build steps are scripted in [complete_build.sh](https://github.com/shrkamat/waystack/blob/master/complete_build.sh)

**Comment by shrkamat** [comment]
BTW I have similar results when attempting to compile this on ubuntu server where we don't have preinstalled Wayland.

To me it looks like meson ignores PKG_CONFIG_PATH export in step 2.

**Comment by xclaesse** [comment]
Sorry went to fast yesterday, I think the issue is PKG_CONFIG_PATH is for host machine dependencies, not build machine. Not sure it works but try PKG_CONFIG_PATH_FOR_BUILD, or -Dbuild.pkg_config_path=
