### ISSUE TITLE
gtkmm-4.0

### ISSUE THREAD

**Issue by hydrasho** [mesonbuild/wrapdb#96]
this is my first script, but it works great however it also provides:
cairomm 1.16
glibmm 2.68
pangomm 2.48
sigc ++ 3.0

so maybe it should also be added in the script in [PROVIDES]? I don't know, do as you see fit ^^

[wrap-git]
directory = gtkmm-4.0

url = https://github.com/GNOME/gtkmm.git
revision = gtkmm-4-0

[provide]
dependency_names = gtkmm-4.0

**Comment by jpakkane** [comment]
The repo for gtkmm has been created, please file a pull request with your patch. Note that it must use one of the releases, as Git checkouts are not supported in WrapDB. Thanks.

https://github.com/mesonbuild/gtkmm

**Comment by hydrasho** [comment]
even a git that points to a single branch? I really do not come with a tar.gz from the source I still try this: but it does not work

[wrap-file]
directory = gtkmm-4.0.0

source_url = https://github.com/GNOME/gtkmm/archive/refs/tags/4.0.0.tar.gz
source_filename = gtkmm-4.0.0.tar.gz
source_hash = 76fac2d66afa73f307080513589c1b185463e43ab38749f9900c1e83e96f91aa

[provide]
dependency_names = gtkmm-4.0, cairomm-1.16

**Comment by hydrasho** [comment]
I found my problem to build gtkmm4 I need all these wraps there:
how can we do it?

[cairomm-1.16.txt](https://github.com/mesonbuild/wrapdb/files/6415704/cairomm-1.16.txt)
[gdk-pixbuf.txt](https://github.com/mesonbuild/wrapdb/files/6415705/gdk-pixbuf.txt)
[glibmm-2.68.txt](https://github.com/mesonbuild/wrapdb/files/6415706/glibmm-2.68.txt)
[gtk4.txt](https://github.com/mesonbuild/wrapdb/files/6415707/gtk4.txt)
[libepoxy.txt](https://github.com/mesonbuild/wrapdb/files/6415708/libepoxy.txt)
[pangomm-2.48.txt](https://github.com/mesonbuild/wrapdb/files/6415709/pangomm-2.48.txt)

**Comment by dnicolodi** [comment]
Why do you want to download the sources from Github? gtkmm is develop along with all the GNOME stack on gitlab.gnome.org, here https://gitlab.gnome.org/GNOME/gtkmm/ gtkmm and source tarballs are here https://download.gnome.org/sources/gtkmm/

**Comment by jpakkane** [comment]
> how can we do it?

We'll add them one by one, assuming you can generate the wrap files or have already done so. Let's start with the one that has the fewest dependencies (i.e. none). Which one is that?

**Comment by jpakkane** [comment]
It depends. If they are in their own projects and have their own releases then tthey all should be separate. If they come from the same repo, then they can all go in the same one and each one gets their own line in the `[provide]` section.

**Comment by hydrasho** [comment]
Suddenly I tell you the progress: I made pangomm.wrap cairomm.wrap and libsigc ++ = 3.0.wrap the problem is that the tar.gz of libsigc ++ 3.0 does not contain a meson file but the 3.6 for example Yes !

and the problem is that cairomm1.16 he wants his 3.0 and not 3.6,

`` cairomm-1.16 | Dependency sigc ++ - 3.0 from subproject subprojects / libsigcplusplus-3.0.6 found: NO

``
[cairomm-1.16.txt](https://github.com/mesonbuild/wrapdb/files/6423165/cairomm-1.16.txt)
[pangomm-2.48.txt](https://github.com/mesonbuild/wrapdb/files/6423166/pangomm-2.48.txt)
[sigc++-3.0.txt](https://github.com/mesonbuild/wrapdb/files/6423167/sigc%2B%2B-3.0.txt)



how to do ?

**Comment by hydrasho** [comment]
![image](https://user-images.githubusercontent.com/40312793/117072011-24101000-ad30-11eb-94c9-4604588c17d7.png)

**Comment by hydrasho** [comment]
I succeeded, libsigc ++ wrap finally works (I did not understand the principle with [provide] I just modeled on another wrap)

well, it's finally progressing ^^ '
