### ISSUE TITLE
icu: 64 and 32 on windows?

### ISSUE THREAD

**Issue by srl295** [mesonbuild/wrapdb#967]
@mcdurdin noticed in downstream 
https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/icu/meson.build#L21-L24

```meson
if host_machine.system() == 'windows'
…
  add_project_arguments('-DWIN32', '-DWIN64', '-D_MBCS', language: 'cpp')
…
  add_project_arguments('-DWIN32', '-DWIN64', '-D_MBCS', language: 'c')
```

so, `WIN32` and `WIN64` are set regardless of whether the build is actually 32 or 64.  Should it be more specific?

**Comment by srl295** [comment]
Actually, ICU's own MSVC files have these.  I don't remember why exactly. So, meson is compatible here.

./source/common/common_uwp.vcxproj:

```xml
<PreprocessorDefinitions>WIN64;WIN32;%(PreprocessorDefinitions)</PreprocessorDefinitions>
```

**Comment by neheb** [comment]
_WIN32 as a macro is present in both 32 and 64-bit on Windows. Seems correct here. Closing.

**Comment by mcdurdin** [comment]
@neheb, _WIN32 is not the same as WIN32.

https://accu.org/journals/overload/24/132/wilson_2223/ seems like a good reference here.

Generally, WIN64 and WIN32 should not both be defined, although this is just a convention. But as @srl295 notes, this is a setting coming from the ICU project sources, so there may be a good reason for it lost in history there?

**Comment by srl295** [comment]
> @neheb, _WIN32 is not the same as WIN32.
> 
> 
> 
> https://accu.org/journals/overload/24/132/wilson_2223/ seems like a good reference here.
> 
> 
> 
> Generally, WIN64 and WIN32 should not both be defined, although this is just a convention. But as @srl295 notes, this is a setting coming from the ICU project sources, so there may be a good reason for it lost in history there?

I'll ask around. I don't know off the top of my head.

**Comment by eli-schwartz** [comment]
It externally sounds like there could be a story here that's similar to the Microsoft story. :D

Fortunately, for a single project working on its own internals the compatibility risks are much lighter, so this could be a good opportunity to clean up an old tech debt. I guess it depends on if the codebase currently relies on both being set for 64-bit Windows, if it does so then that cleanup would probably require new source code to go along with a build system tweak.
